### ISSUE TITLE
Missing jsbeautifier dependency?

### ISSUE THREAD

**Issue by tbarchyn** [thedirtyfew/dash-extensions#103]
Clean virtual environment install of the normal dash stack - with dash-leaflet and dash-extensions 0.0.60 installed with `pip install dash-extensions` fails as it could not import jsbeautifier.

Possibly it is a missing dependency?

`pip install jsbeautifier` fixes the problem

**Comment by emilhe** [comment]
I initially didn't include it as mandatory dependency, as it is only needed for the `javascript` module. However, the lib is rather small (< 100 kB), so I guess it might be better just to include it per default. I have done that how, so the issue should be fixed on the next release.
