### ISSUE TITLE
Keyboard should catch only events outside of input fields

### ISSUE THREAD

**Issue by FranzForstmayr** [thedirtyfew/dash-extensions#104]
Hi,

First of all, thanks for this great addition to Dash!

I have a Dash Webapp and use the `Keyboard` Component to switch between a few tabs.
There's a button to download some content of the application, and a text input to specify the name of the downloaded file.

Everytime I hit the specific key inside the input, the `Keyboard` component triggers. 
Is there a way, to catch only keystrokes outside of any input field?

Thanks
Franz

**Comment by emilhe** [comment]
Close due to the `Keyboard` component being deprecated.

**Comment by PepijnBoers** [comment]
Hi @emilhe,
What is the current alternative for the `Keyboard` component? I can't seem te find any. My goal is to create simple shortcuts that trigger different callbacks.
Thanks,
Pepijn
