### ISSUE TITLE
unpkg.com 404

### ISSUE THREAD

**Issue by danielmitchell** [thedirtyfew/dash-extensions#109]
I am using dash with `serve_locally=False` in order to serve js/css from a cdn.

I am getting a 404 error for the external assets for this package. Other packages are working correctly.

The URL for one of the assets is `https://unpkg.com/dash_extensions@0.0.65/dash_extensions/dash_extensions.min.js`

`dash_extensions@0.0.65` doesn't exist on npm/unpkg package. They only have `dash-extensions@0.0.1`.

Thanks for this great library.

**Comment by emilhe** [comment]
This reason you are seeing the behaviour is that I created a dash-extensions npm package to be used for javascript developers, that's the package that you have found. Now that I think about it, I should probably have named it differently...

**Comment by danielmitchell** [comment]
Ok that makes sense that you have a different package with a similar name, but what about the assets for this package? It is trying to load external assets from the cdn that don't exist.

**Comment by emilhe** [comment]
Closed due to inactivity.

**Comment by landert** [comment]
Hi, any update on this please? I'm using dash-extensions-0.1.13 and I'm still getting 404 for this URL:
```
https://unpkg.com/dash_extensions@0.1.13/dash_extensions/dash_extensions.min.js
```

**Comment by cesarqdt** [comment]
+ 1
