### ISSUE TITLE
Keyboard not updating for repeated key press

### ISSUE THREAD

**Issue by thisiscam** [thedirtyfew/dash-extensions#11]
The keyboard example in the README.md does not work, if the same key is pressed >=2 times (i.e. press -> release -> press).
The expected behavior, at least for me, is that the keyboard event should be signaled twice, even for the same key.
The current behavior is that it ignores the key presses. This is due to the implementation uses keydown as a prop, which is not changed for the same key press event (by shallow comparison).

**Comment by emilhe** [comment]
It is the general convention in Dash that callbacks are only fired, when a property _changes_. If you press the key twice, the value does not change and the callback not firing is expected behavior. 

That being said, i agree that it is a limitation that subsequent key presses cannot be captured. One possible solution could be to add an `n_keydowns` (like `n_clicks` for buttons) property, which changes every time a key press event occurs. What do you think?

**Comment by thisiscam** [comment]
@emilhe Yes, `n_keydowns` seems like complaint with the standard html components as I just found out. 

Would you (or the maintainer of this repo, whoever that may apply) want a PR? 
Or I can also wait for this to be fixed, though this is kind of blocking me (I also kind of don't want to roll my own component just for this), so it will be good to know what's the priority of this for the maintainer, thanks!

**Comment by emilhe** [comment]
I am always happy to look at a PR :). But this seems like a rather simple feature, so i just made an attempt to implement it right away. You can try it out here,

https://pypi.org/project/dash-extensions/0.0.29rc1/

Let me know if it works as intended and/or you have ideas on how to improve the syntax.

**Comment by thisiscam** [comment]
@emilhe Wow thanks for the quick update!

```python
import dash
import dash_html_components as html
import json

from dash.dependencies import Output, Input, State
from dash_extensions import Keyboard

app = dash.Dash()
app.layout = html.Div([Keyboard(id="keyboard"), html.Div(id="output")])


@app.callback(Output("output", "children"), [Input("keyboard", "n_keydowns")],
              [State("keyboard", "keydown")])
def keydown(n_keydowns, event):
  print(event, n_keydowns)
  return json.dumps(event)


if __name__ == '__main__':
  app.run_server(debug=True)
```

I was trying the above and ran into the following JS errors: 
```
react_devtools_backend.js:2273 Error: Invalid argument `n_keydowns` passed into Keyboard with ID "keyboard".
Expected `object`.
Was supplied type `number`.
Value provided: 1
```

The only essential difference between your example and mine is the `app.run_server(debug=True)`. Seems like under debug mode some JS type assertion is triggered?

**Comment by emilhe** [comment]
Ah, yes. I made a mistake in the prop definition. Try (0.0.29rc2),

pip install https://files.pythonhosted.org/packages/51/bd/4aae6a805f13ed829897255a10224af5d0f3cbf38de9bb242e207abfb441/dash-extensions-0.0.29rc2.tar.gz

https://pypi.org/project/dash-extensions/0.0.29rc2/

**Comment by thisiscam** [comment]
Works perfectly! Many thanks for the quick update! 🥇

**Comment by mfreeborn** [comment]
May I please suggest that the n_keydowns property gets added to the README? I think it's a crucial feature, to be able to catch multiple of the same key presses in a row, but I had to dig through the source code/closed issues to find it! Thank you very much for this useful library.

**Comment by mfreeborn** [comment]
See #47

**Comment by vcmorini** [comment]
This thread helped me as well. Thanks.
---
_Problem:_ If you press the keys too fast, it creates several callbacks.
_Ideas:_ Maybe a way to prevent the key press event before finishing the execution of the previous callback.
Or, maybe simpler, setting a minimum time between 2 key press events, such as 0.5s.

**Comment by MalcolmDrummond** [comment]
Hi Emilhe. I think the component needs to update on key-up, otherwise it's maintaining a key-down status for keys after they've been released. I ran into this while checking for alt-click and ctrl-click on a plot (Input is clicks, State is keydown).
