### ISSUE TITLE
got errors, when using long_callback

### ISSUE THREAD

**Issue by 630362055** [thedirtyfew/dash-extensions#110]
![image](https://user-images.githubusercontent.com/25970108/143915002-b8673c55-d1ea-4f03-b70e-a184d25ff4b9.png)

```
app = DashProxy(external_stylesheets=external_stylesheets,meta_tags=[{
                        "name": "viewport",
                        "content": "width=device-width, initial-scale=1, maximum-scale=1"
                    }])
@app.long_callback(
    output=Output('raw_data_cleaning_state', 'children'),
    inputs=[Input('clean_raw_data_button', 'n_clicks'),
            State('username', 'data'),
            State('file_list_completedata', 'value')
            ],

    running=[(Output('clean_raw_data_button', 'disabled'), True, False),
             (Output('clean_raw_data_button', 'children'), 'wait for processing', 'Clean the selected data')],
    prevent_initial_call=True,
    manager=long_callback_manager
)
```
When use the dash.Dash, it works fine

```
app = dash.Dash(__name__,
                #suppress_callback_exceptions=True,
                external_stylesheets=external_stylesheets,
                #long_callback_manager=long_callback_manager,
                # prevent_initial_callbacks=True,
                # routes_pathname_prefix='/dash/',
                # It's what make the app be responsive;

                meta_tags=[{
                        "name": "viewport",
                        "content": "width=device-width, initial-scale=1, maximum-scale=1"
                    }])
```

**Comment by emilhe** [comment]
The transform system was implemented prior to Dash 2.0, so it doesn't apply to Dash 2.0 callbacks (i.e. long callbacks and callbacks "directly on the dash module"). I have updated the documentation accordingly.

**Comment by warrenalphonso** [comment]
Thanks for your work on this project, @emilhe! Are you planning on adding support for `long_callback`? Is there something that makes it hard to support it?

**Comment by emilhe** [comment]
I don't see any immediate blockers, but as the structure is different from other callbacks, it will probably require a bit of work.

The main reasons I haven't prioritized (looking into) support yet is that not many people seem to use the feature, myself included.

**Comment by cjstudioz** [comment]
is there still a way to call the original Dash long_callback within the same app if that particular callback doesn't require any of the DashProxy enrich transforms?

**Comment by emilhe** [comment]
No, you'll have to use the new syntax.
