### ISSUE TITLE
MultiplexerTransform does not work with Dash 2.0 style callback decoration

### ISSUE THREAD

**Issue by xwk** [thedirtyfew/dash-extensions#111]
My test shows MultiplexerTransform is not working if you use dash.callback decorator as suggested by Dash 2.0 (instead of app.callback).  The error message is "Duplicate callback outputs"

The test code is as below

```
import dash
import dash_html_components as html
from dash_extensions.enrich import Output, DashProxy, Input, MultiplexerTransform

app = DashProxy(prevent_initial_callbacks=True, transforms=[MultiplexerTransform()])
app.layout = html.Div([html.Button("left", id="left"), html.Button("right", id="right"), html.Div(id="log")])


@dash.callback(Output("log", "children"), Input("left", "n_clicks"))
def left(_):
    return "left"


@dash.callback(Output("log", "children"), Input("right", "n_clicks"))
def right(_):
    return "right"


if __name__ == '__main__':
    app.run_server(debug=True, port=7777)
```

**Comment by emilhe** [comment]
The transform system was implemented prior to Dash 2.0, so it doesn't apply to Dash 2.0 callbacks (i.e. long callbacks and callbacks "directly on the dash module"). I have updated the documentation accordingly.

**Comment by emilhe** [comment]
I have just pushed a new 0.0.66 release, which should resolve the issue. Please try it out and report back if it solves your issue.

**Comment by xwk** [comment]
@emilhe sorry for the late response. I confirm the fix works. However, there is another related issue. I created a new ticket for that  https://github.com/thedirtyfew/dash-extensions/issues/125
