### ISSUE TITLE
ImportError: cannot import name 'Input' from 'dash' 

### ISSUE THREAD

**Issue by benmelman** [thedirtyfew/dash-extensions#117]
Hi, getting an import error when trying to import the enrich component: 

I have installed dash-extensions but when trying to run the following: 

```
from dash_extensions.enrich import Dash, ServersideOutput, Output, Input, State, Trigger

```

```
     9 
     10 # Enable enrich as drop-in replacement for dash
---> 11 from dash import no_update, Input, Output, State, ClientsideFunction, MATCH, ALL, ALLSMALLER, development, exceptions, \
     12     resources, dcc, html, dash_table, callback_context, callback, clientside_callback
     13 from dash.dependencies import _Wildcard

ImportError: cannot import name 'Input' from 'dash' 
```

What am i doing wrong? 

Thank you,

**Comment by emilhe** [comment]
What version of Dash are you on? Recent versions of dash-extensions require Dash 2.0

**Comment by simstoykov** [comment]
I think pinning `dash` to a version "<2" should fix this.

Is there a way to pin `dash` as part of the requirements in older versions of `dash-extensions`, so that dependency solvers automatically install the correct one?

**Comment by benmelman** [comment]
Updating dash to latest version resolved this issue.  Thank you.
