### ISSUE TITLE
Silly question: Why is this not in dash project itself?

### ISSUE THREAD

**Issue by jfftonsic** [thedirtyfew/dash-extensions#12]
Hello, 
The features that this project provides seem sufficiently important and I'd guess useful for most people that use dash itself.
Is there a reason why all this implementation is not part of dash itself?

PS: this probably is not the place for this kind of question, but I didn't know where else to ask it.

**Comment by emilhe** [comment]
Dash itself is a UI library developed by the plotly organisaion. On the other hand, `dash-extensions` is just a collection of code snippets that i have been reusing across projects. But i am happy to know that you find them useful :)

**Comment by jfftonsic** [comment]
Oh, thanks for answering. I thought dash's code was like open-source/community code that could receive pull requests! 
It is certainly useful, it deals with some of the grips that I time and again hit with dash.
Cheers
