### ISSUE TITLE
MultiplexerTransform does not work with Dash 2.0 flexible callback signature

### ISSUE THREAD

**Issue by xwk** [thedirtyfew/dash-extensions#125]
One major feature of Dash 2.0 is the flexible callback signature. In particular, you can give each output or input dependency a name. However, my test shows MultiplexerTransform does not work with this feature. The test code is as below

```import dash
from dash import html
from dash_extensions.enrich import Output, DashProxy, Input, MultiplexerTransform, callback

app = DashProxy(prevent_initial_callbacks=True, transforms=[MultiplexerTransform()])
app.layout = html.Div([html.Button("left", id="left"), html.Button("right", id="right"), html.Div(id="log")])


@callback(
    output={
        'log': Output("log", "children")
    },
    inputs={
        '_': Input("left", "n_clicks")
    }
)
def left(_):
    return {
        'log': "left"
    }


@callback(
    output={
        'log': Output("log", "children")
    },
    inputs={
        '_': Input("right", "n_clicks")
    }
)
def right(_):
    return {
        'log': "right"
    }


if __name__ == '__main__':
    app.run_server(debug=True, port=7777)
```
When you run the code above, you will see multiple errors being thrown, including 'A callback is missing Inputs', 'A callback is missing Outputs', 'Duplicate callback outputs', etc.

Tested on dash-extension v0.0.69

**Comment by emilhe** [comment]
Ah, yes, that syntax has not (yet) been adopted. I don't see any technical issues in enabling this syntax too. But I will take a bit of work.

**Comment by xwk** [comment]
Verified. Thanks for the fix.
