### ISSUE TITLE
Not supporting dash's callbacks when you name the parameters

### ISSUE THREAD

**Issue by jfftonsic** [thedirtyfew/dash-extensions#13]
Hi again,
I tried to use your mod today and after changing the imports, the application failed to start and after an easy glance it was because my callbacks were being defined like the following example:
```
        @app.callback(
            output=[ ... ],
            inputs=[ ... ],
            state=[ ... ]
        ) ....
```
which is one of the ways that pure dash lets you define the callback. The problem happens because I used the 'output=...' etc to define the parameters.

I already have implemented a modification directly in my workspace, on the error point which is in enrich.py. It is very simple really.

I will go on and try to fork, etc to submit a pull request to your project. Unless I shouldn't do that, then let me know.

Cheers

**Comment by emilhe** [comment]
Ah, yes, i didn't include that use case. I am always happy to look at a pull request :+1:

**Comment by emilhe** [comment]
Thanks! I just made a new build that includes your code,

https://pypi.org/project/dash-extensions/0.0.32rc5/

If you can confirm that it's working as intended, i will create a pypi release :)

**Comment by jfftonsic** [comment]
Cool, you improved the code :)

It is working. Thanks!
