### ISSUE TITLE
Serversideoutput cannot be input, updated, and output in a single callback

### ISSUE THREAD

**Issue by ajcost** [thedirtyfew/dash-extensions#130]
I have an issue with the following callback:

```python
# Configure main scenario poi model for control panel selection
app.callback(
    ServersideOutput(id("model-poi-main-scenario"), "data"),
    [
        Trigger(id("compare-view-execute-button"), "n_clicks"),
        Trigger(id("country-execute-button"), "n_clicks"),
        Input(id("model-poi-main-scenario"), "data"),
    ],
    State(id("main-view-poi-dropdown"), "value"),
)(sea_level_rise_storm_surge_poi_update_callback)
```

This call back is raising an error 
```
AttributeError: 'Output' object has no attribute 'backend'
```

Which resides on line 513 in enrich.py

The poi model is build in another callback and in this callback I want to update the poi model. I would like to update the store with the updated model. But when I run these callbacks specifically it fails. Seemingly its impossible to update a ServersideOutput with itself as an Input?

There are two ways to go about doing this. Either the cache maintains the same object and the callback doesn't copy the object and just updates in the function or have a function that can take and Input as the serverside object and update the store id in the serverside output.

Wondering if this is an issue or I'm tackling this problem in the wrong way.

The final solution is to make two stores with two models, a store called hidden and then the actual one. And updates the model take the model from the hidden store and update it and then update that with the main model store. See below:

```python
app.callback(
    ServersideOutput(id("model-poi-main-scenario"), "data"),
    [
        Trigger(id("compare-view-execute-button"), "n_clicks"),
        Trigger(id("country-execute-button"), "n_clicks"),
        Input(id("model-poi-main-scenario-hidden"), "data"),
    ],
    State(id("main-view-poi-dropdown"), "value"),
)(sea_level_rise_storm_surge_poi_update_callback)
```

However this I believe is pretty inelegant and unnecessarily fills cache space. If the first solution worked without throwing an error I would be happy.

**Comment by ajcost** [comment]
I'm using the Dash object which contains all transforms

**Comment by emilhe** [comment]
I am asking because it is not possible to use the same server side output in multiple callbacks, which it is sounds like you might be doing.

**Comment by emilhe** [comment]
It does help with that issue, but only for normal outputs. Server side ouputs are currently not supported.

**Comment by ajcost** [comment]
I suppose shall close the issue then thanks for the help
