### ISSUE TITLE
[Multipage] navigate to page inside callback

### ISSUE THREAD

**Issue by befedo** [thedirtyfew/dash-extensions#134]
Hi there,

I've set up a [multipage](https://github.com/thedirtyfew/dash-extensions#multipage) app like shown in the examples. I would like to navigate to another page from inside a callback (for example a specific `dcc.Dropdown` value selected, not using `dbc.Select`), I've added a hidden `Div` with a `Button` to my layout and changed the buttons href and n_clicks attributes from inside the callback but no page navigation is done.

Are there options to navigate to another page from inside a callback?

Thanks for your time and effort on this nice extension!
Best regards,
Befedo

**Comment by emilhe** [comment]
Closed due to `multipage` module being deprecated.
