### ISSUE TITLE
Specify known limitations more precisely

### ISSUE THREAD

**Issue by frnhr** [thedirtyfew/dash-extensions#136]
In MultiplexerTransform section of the readme, there is a [Known Limitations section](https://github.com/thedirtyfew/dash-extensions#know-limitations) which reads:

> ##### Know limitations
> The MultiplexerTransform does not support the MATCH and ALLSMALLER wildcards. The MultiplexerTransform does not support ServersideOutput.

For me this can mean one of two things:

1. When using the multiplexer we cannot use `MATCH` _anywhere_ in your app, OR
2. We actually can use `MATCH` _as long as_ that specific callback doesn't use the multiplexer (i.e. it has a unique `Output`).

Which is the correct reading?

Ditto for the other limitation about `ServersideOutput`, as well as the limitation for `long_callback` mentioned a few lines above the linked section.

**Comment by emilhe** [comment]
The correct reading is (2). I should probably make that more clear in the docs :)

**Comment by emilhe** [comment]
Docs have been updated.
