### ISSUE TITLE
[Multipage] Callbacks stop triggering after repeated navigation.

### ISSUE THREAD

**Issue by vmatos** [thedirtyfew/dash-extensions#141]
I followed the example on how to achieve Multipage using dash-extensions.

Everything works as expected, until you repeatedly navigate through the pages. Once you return to a previously visited page, the callbacks no longer work/trigger.

I need to restart the application for the callbacks to trigger again, but once I navigate a second time to a given page, the callback will not trigger once again.

Versions:
* dash: 2.2.0
* dash extensions: 0.0.71

Do you have any suggestion on how can I troubleshoot the issue?

Minimal example of issue:

`minimal_app.py`:

```
from dash import dcc, html
from dash_extensions.enrich import DashProxy, Input, Output
from dash_extensions.multipage import PageCollection, app_to_page, module_to_page, Page, CONTENT_ID, URL_ID

import pages.minimal_page as module

def simple_menu(page_collection):
    children = []
    pages = page_collection.pages
    for i, page in enumerate(pages):
        children.append(html.A(children=page.label, href="/{}".format(page.id)))
        if i < (len(pages) - 1):
            children.append(html.Br())
    return children

# Create pages.
pc = PageCollection(
    pages=[
        module_to_page(module, id="page1", label="Page 1"),
        module_to_page(module, id="page2", label="Page 2"),
        module_to_page(module, id="page3", label="Page 3"),
    ]
)

# Create app.
app = DashProxy(suppress_callback_exceptions=True)
app.layout = html.Div(simple_menu(pc) + [html.Div(id=CONTENT_ID), dcc.Location(id=URL_ID)])
# Register callbacks.
pc.navigation(app)
pc.callbacks(app)


if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=8080, debug=True,
     dev_tools_silence_routes_logging=False)
```

`pages/minimal_page.py`

```
from dash_extensions.enrich import Input, Output
from dash import html, dcc

def layout(*args, **kwargs):
    url_prefix = args[0]

    return html.Div(children=[
            html.Br(),
            dcc.Input(id="input", value=url_prefix),
            html.Div(id="output"),
            ]
        )


def callbacks(app):
    @app.callback(Output("output", "children"), [Input("input", "value")])
    def hello_vacuum(value):
        print('Hello: ', value)
        return f"Page says: {value}!"
```

Additional point:

I had the assumption that by adopting `dash_extensions.multipage`, I would not get `ID not found in layout`.

**Comment by vmatos** [comment]
When running the provided `multipage_app.py` example from `dash-extensions`, only the pages from `Page` and `module_to_page` exhibit this issue.

When I run the following minimal example, with pages created from `app_to_page`, everything works as expected.

**`minimal_app.py`:**

```
from dash import dcc, html
from dash_extensions.enrich import DashProxy, Input, Output
from dash_extensions.multipage import PageCollection, app_to_page, module_to_page, Page, CONTENT_ID, URL_ID

import pages.minimal_app as module

def simple_menu(page_collection):
    children = []
    pages = page_collection.pages
    for i, page in enumerate(pages):
        children.append(html.A(children=page.label, href="/{}".format(page.id)))
        if i < (len(pages) - 1):
            children.append(html.Br())
    return children

# Create pages.
pc = PageCollection(
    pages=[
        app_to_page(module.build('/page1'), id="page1", label="Page 1"),
        app_to_page(module.build('/page2'), id="page2", label="Page 2"),
        app_to_page(module.build('/page3'), id="page3", label="Page 3"),
    ]
)

# Create app.
app = DashProxy(suppress_callback_exceptions=True)
app.layout = html.Div(simple_menu(pc) + [html.Div(id=CONTENT_ID), dcc.Location(id=URL_ID)])
# Register callbacks.
pc.navigation(app)
pc.callbacks(app)


if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=8080, debug=True,
     dev_tools_silence_routes_logging=False)
```

**`pages/minimal_app.py`:**

```
from dash_extensions.enrich import DashProxy, Input, Output
from dash import html, dcc

def build(label):
    app = DashProxy()
    app.layout = html.Div(children=[
                    html.Br(),
                    dcc.Input(id="input", value=label),
                    html.Div(id="output"),
                    ]
                )

    @app.callback(Output("output", "children"), [Input("input", "value")])
    def hello(value):
        print('Hello: ', value)
        return f"Page says: {value}!"

    return app
```

**Comment by vmatos** [comment]
> I followed the example on how to achieve Multipage using dash-extensions.
> 
> Everything works as expected, until you repeatedly navigate through the pages. Once you return to a previously visited page, the callbacks no longer work/trigger.
> 
> I need to restart the application for the callbacks to trigger again, but once I navigate a second time to a given page, the callback will not trigger once again.
> 
> Versions:
> 
>     * dash: 2.2.0
> 
>     * dash extensions: 0.0.71
> 
> 
> Do you have any suggestion on how can I troubleshoot the issue?
> 
> Minimal example of issue:
> 
> `minimal_app.py`:
> 
> ```
> from dash import dcc, html
> from dash_extensions.enrich import DashProxy, Input, Output
> from dash_extensions.multipage import PageCollection, app_to_page, module_to_page, Page, CONTENT_ID, URL_ID
> 
> import pages.minimal_page as module
> 
> def simple_menu(page_collection):
>     children = []
>     pages = page_collection.pages
>     for i, page in enumerate(pages):
>         children.append(html.A(children=page.label, href="/{}".format(page.id)))
>         if i < (len(pages) - 1):
>             children.append(html.Br())
>     return children
> 
> # Create pages.
> pc = PageCollection(
>     pages=[
>         module_to_page(module, id="page1", label="Page 1"),
>         module_to_page(module, id="page2", label="Page 2"),
>         module_to_page(module, id="page3", label="Page 3"),
>     ]
> )
> 
> # Create app.
> app = DashProxy(suppress_callback_exceptions=True)
> app.layout = html.Div(simple_menu(pc) + [html.Div(id=CONTENT_ID), dcc.Location(id=URL_ID)])
> # Register callbacks.
> pc.navigation(app)
> pc.callbacks(app)
> 
> 
> if __name__ == '__main__':
>     app.run_server(host='0.0.0.0', port=8080, debug=True,
>      dev_tools_silence_routes_logging=False)
> ```
> 
> `pages/minimal_page.py`
> 
> ```
> from dash_extensions.enrich import Input, Output
> from dash import html, dcc
> 
> def layout(*args, **kwargs):
>     url_prefix = args[0]
> 
>     return html.Div(children=[
>             html.Br(),
>             dcc.Input(id="input", value=url_prefix),
>             html.Div(id="output"),
>             ]
>         )
> 
> 
> def callbacks(app):
>     @app.callback(Output("output", "children"), [Input("input", "value")])
>     def hello_vacuum(value):
>         print('Hello: ', value)
>         return f"Page says: {value}!"
> ```
> 
> Additional point:
> 
> I had the assumption that by adopting `dash_extensions.multipage`, I would not get `ID not found in layout`.

**Comment by AlexanderZender** [comment]
Can confirm, this same behavior is happening with my application.
Any Idea or update would be appreciated!

**Comment by emilhe** [comment]
Closed due to `multipage` module deprecation.
