### ISSUE TITLE
ImportError: cannot import name 'Input' from 'dash'

### ISSUE THREAD

**Issue by ruihou1** [thedirtyfew/dash-extensions#146]

**Comment by emilhe** [comment]
What version of Dash are you running? You must use at least 2.0

**Comment by ruihou1** [comment]
my dash is 2.2.0 but the same error is displayed

**Comment by emilhe** [comment]
Could you post an MWE demonstrating  the issue?

**Comment by emilhe** [comment]
Closed due to inactivity.

**Comment by anfoss** [comment]
This is happening to me too. I am using a virtual env with Dash 2.3.1

`(base) andreafossati@Andreas-MacBook-Pro % conda list | grep dash
dash                      2.3.1                    pypi_0    pypi
dash-bootstrap-components 1.1.0                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-renderer             1.1.2                      py_0  
dash-table                5.0.0                    pypi_0    pypi`
