### ISSUE TITLE
What needs to be done to get integrate long_callbacks with dash-extensions?

### ISSUE THREAD

**Issue by pjaselin** [thedirtyfew/dash-extensions#150]
Curious to see what you need to do to get long_callbacks working with dash-extensions and I'm happy to pitch in if you'd like. Also I love this library and have used it all the time these past few years!

**Comment by emilhe** [comment]
Thanks! I am working on a major update that adds tests and interactive documentation, so I haven't looket at it yet. But I imagine creating an intermediate layer, similar to the one implemented for callbacks and clientside callbacks.

**Comment by pjaselin** [comment]
Gotcha sounds good, I'll have to work on better understanding how your intermediate layer works for the regular callbacks.

**Comment by emilhe** [comment]
The update has now been migrated into master. Hence, I will expect the structure to remain more stable from now on :)

**Comment by pjaselin** [comment]
Ok sounds good thanks! I'll update my master then

**Comment by pjaselin** [comment]
I think this can be closed now that long_callback is being deprecated in favor of background callbacks: https://dash.plotly.com/background-callbacks. This has worked for me in conjunction with dash-extensions.
