### ISSUE TITLE
Help wanted! MultiplexerTransform doesn't fire callback

### ISSUE THREAD

**Issue by zillionare** [thedirtyfew/dash-extensions#154]
dash                           2.3.1
dash-bootstrap-components      1.1.0
dash-core-components           2.0.0
dash-extensions                0.0.71
dash-html-components           2.0.0
dash-table                     5.0.0

the code:
`
from dash_extensions.enrich import (
    DashProxy,
    TriggerTransform,
    MultiplexerTransform,
    ServersideOutputTransform,
    NoOutputTransform,
    LogTransform,
)

from alpha.web import routing # home made router to switch between pages

app = DashProxy(
    __name__,
    external_stylesheets=[dbc.themes.MATERIA, dbc.icons.FONT_AWESOME],
    suppress_callback_exceptions=True,
    assets_folder=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "web/assets"
    ),
    prevent_initial_callbacks=True,
    transforms=[
        MultiplexerTransform(),
        TriggerTransform(),
        ServersideOutputTransform(),
        NoOutputTransform(),
        LogTransform(),
    ],
)
`
@app.callback(Output("main-fig", "figure"), 
Input("stock-input", "value"), Input("stock-input", "n_submit"))
def on_stock_change(code: str, n_submit:int):
    sid = "hello"
    if not validate_code(sid, code):
        return dash.no_update

    figure = make_main_figure(sid)
    return figure

@app.callback(
    Output("main-fig", "figure"),
    Input("session-id", "data"),
    Input("stock-input", "value"),
    Input("date-input", "value")
)
def on_params_change(sid: str, code, date):
    triggered = get_triggerred_controls()
`

callbacks doesn't fired.

If I remove DashProxy and merge callbacks, the program works.

Please help me how to troubleshooting the issue. No exceptions at both client side and server side

**Comment by zillionare** [comment]
by the way, it's a great extension and I love it!

**Comment by emilhe** [comment]
Could you post a conplete example, i.e. a block of code that runs?

**Comment by zillionare** [comment]
Closed this issue. Usually these issues are caused by wrong element id, but dash doesn't report missing element id everytime.
