### ISSUE TITLE
WebSocket Examples

### ISSUE THREAD

**Issue by tljstewart** [thedirtyfew/dash-extensions#159]
O man, looks likes some restructuring of the codebase, was really trying to study the websocket `examples/websocket_update.py` to get it working, any ideas on how I can make that happen or have the updates changed the way websockets work?

**Comment by tljstewart** [comment]
Hmm found this https://www.dash-extensions.com/components/websocket

**Comment by emilhe** [comment]
Yep, those are the updated docs. Some of the old examples relied on deprecated libraries.

**Comment by tljstewart** [comment]
for what it's worth, wanted to confirm I was able to get that demo in the link running easily. (albeit, I had to change the default port for the web app, but I think it's bc I had `8050` used)

Thanks for the good documentation
