### ISSUE TITLE
Cannot access docs page

### ISSUE THREAD

**Issue by mayurpande** [thedirtyfew/dash-extensions#175]
I tried to follow the link provided to the docs https://www.dash-extensions.com/ but I get a site cannot be reached error.

**Comment by emilhe** [comment]
Hmm, that's interesting. It works fine here. What OS/Browser are you on? Can you reach render.com (which is the hosting provider)?

**Comment by mayurpande** [comment]
I am on windows 10 and google chrome, I can access render.com, I tried on edge as well, but still same issue, maybe to do with my work proxy, I will check later on my laptop when I get home.

**Comment by mayurpande** [comment]
Yes seems it must be a proxy issue with my work which is bizarre. I am able to access the docs page on my phone. I will ask my IT department.
