### ISSUE TITLE
Method for download file / send file with b64 encoded buffer

### ISSUE THREAD

**Issue by zach-morris** [thedirtyfew/dash-extensions#18]
I'd like to use your Download dash-extension for sending a pdf to a user.
I can create the pdf using pdfrw and then generate a base64 encoded file as follows:
```
buf = io.BytesIO()
pdfrw.PdfWriter().write(buf, my_pdf_data)
buf.seek(0)
data_out = base64.encodebytes(buf.read()).decode()
```
I've attempted to use the raw download method:
```
dict(content=data_out , filename="my_pdf.pdf")
```

But the resultant file is not correctly formatted (if the data_out isn't b64 encoded then the method complains about not being JSON serializable).  I see the ```send_bytes``` method, but I'm not sure how to use it for my case.  Could an example be added for this?

Thanks in advance

**Comment by emilhe** [comment]
If you are sending base64 encoded data, you should add base64=True, 

```
dict(content=data_out , filename="my_pdf.pdf", base64=True)
```

If you use the send_bytes, it should be something along the lines of,

```
send_bytes(lambda buf: pdfrw.PdfWriter().write(buf, my_pdf_data), filename="my_pdf.pdf")
```

If you post an MWE that runs (i.e. including some dummy pdf data), i can make a full example.

**Comment by zach-morris** [comment]
Thanks @emilhe for the quick response.

Method #1 fails:
```
return dict(content=data_out, filename='my_pdf.pdf', mime_type='application/pdf', base64=True)
```
results in a callback error:
```
Invalid string. Length must be a multiple of 4
...
l@http://127.0.0.1:8000/_dash-component-suites/dash_extensions/dash_extensions.v0_0_31m1602000320.min.js:1:9696
```

Method #2 works great:
```
return send_bytes(lambda buf: pdfrw.PdfWriter().write(buf,data_out), filename="my_pdf.pdf",mime_type='application/pdf')
```
