### ISSUE TITLE
'DashProxy' object has no attribute 'reactive'

### ISSUE THREAD

**Issue by tenshis** [thedirtyfew/dash-extensions#182]
I found [this post ](https://community.plotly.com/t/reactive-variables/54577)from last year from Emil where a new functionality, reactive variables ("@app.reactive") is discussed as a release candidate. I'm trying to use it now but I can't seem to find it anywhere. All I get is

`'DashProxy' object has no attribute 'reactive'`

**Comment by emilhe** [comment]
Yes, the concept was discussed, but it never made it into production. That's why you can't find it (:

**Comment by tenshis** [comment]
Okay, thank you
