### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by akshayshende129** [thedirtyfew/dash-extensions#19]
Collecting dash-extensions==0.0.31 (from -r requiremnets.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/72/60/52af601da27fb2d57828138746326a356976347e3554df2854695816a06b/dash-extensions-0.0.31.tar.gz (329kB)
    100% |████████████████████████████████| 337kB 2.9MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l2Fdzu/dash-extensions/setup.py", line 15, in <module>
        README = (HERE / "README.md").read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'

Not able to install dashextensions in Ubuntu env.

**Comment by emilhe** [comment]
What version of Python are you using? It seems like you are missing pathlib, which should be available in any modern Python environment (3.5+),

https://github.com/aio-libs/aiohttp/issues/3977

**Comment by akshayshende129** [comment]
python --version
Python 3.6.9

Pathlib is installed, within the environment.

**Comment by akshayshende129** [comment]
Upgrading pip to 20.X.X solved the error.
