### ISSUE TITLE
Can i install this lib without pip or conda

### ISSUE THREAD

**Issue by nchesk** [thedirtyfew/dash-extensions#203]
I need to find a way to clone lib on a pc without internet at all so i was wondering how can i move this lib, because conda or pip isnt option here

**Comment by emilhe** [comment]
You can download the latest release from pypi,

https://files.pythonhosted.org/packages/bf/1c/146826c93a54d0370d3e26776e31214f87221560a27678983bb3f392bcba/dash-extensions-0.1.5.tar.gz

copy the file to "/some_path/dash-extensions-0.1.5.tar.gz" in the destitation pc, and install it via pip,

`pip install /some_path/dash-extensions-0.1.5.tar.gz`
