### ISSUE TITLE
new feature: composed components

### ISSUE THREAD

**Issue by sdementen** [thedirtyfew/dash-extensions#21]
hello @emilhe 

Given you in depth knowledge of Dash and the fact dash-extensions already provide an enhanced Input/Output/State/Trigger layer, I was wondering if you could have a look at the thread https://community.plotly.com/t/build-a-composed-component-in-python/45913/12 ... but you may be the Emil on the community forum ;-)
If it should not land in some dash core library, I feel your library would be the best alternative to host this kind of feature!

The proposal of oegedijk is close yet it does not provide the encapsulation, i.e. the ability to hide the properties of the children components and declare new properties for the composed component. I was thinking about some mapping between "some-new-property" -> Tuple("component-id1.property-name1", "component-id2.property-name2, ...) that could be transparently handled/converted/transformed by your custom Input/Output/State/Trigger classes.

seb

**Comment by emilhe** [comment]
Yes, that's me on the forum ;)

As compared to the suggestion from oegedijk, i guess the input/output/state/trigger layer of dash-extensions could help getting rid "register callbacks" part, which would improve the syntax. However, as noted by oegedijk, a key issue remains; the component can't be stateful. Getting around this limitation would require some kind of linking of the component to a client, e.g. via a `Store` component holding the data or a session key (+ some server side storage with the data).

In any case, if the implementation is done only in Python, the composed component will be "more like an app", as you put it, e.g. properties can be linked only via callbacks (but if you are only after a property renaming, that is definitely doable). 

Your suggestion also leads my thoughts towards component synchronization (e.g. synchronization of the value of an `Input` and a `Slider` component), which there is currently no elegant way to achieve. I would be great with a component that could compose other dash components and synchronize selected properties.

**Comment by sdementen** [comment]
Indeed, I am looking at "keeping in sync" a set of components that are functionally connected.
A simple renaming of properties could be enough, specially if it can be combined with a Store (when the "join" of all components properties is not enough to keep the state of the composed component).
Internally, for linking properties of components for a given composed component, I think reusing the callback approach could lower the learning curve (rather than using another syntax/approach)

**Comment by emilhe** [comment]
Just for reference, i'll just add here that a `Monitor` component has now been added, 

https://github.com/thedirtyfew/dash-extensions/blob/master/examples/monitor.py

which might make it easier to synchronize state.

**Comment by sdementen** [comment]
The composed component may be used for component synchronization and Monitor is an alternative. Yet, the real value of composed components is to be able to write modular dash apps (pages, complex components that manage business objects, ...)
