### ISSUE TITLE
Question on module structure

### ISSUE THREAD

**Issue by shouldsee** [thedirtyfew/dash-extensions#213]
Thanks for writing this great library!

Sorry if I am missing something, but would be great if you could help explains where this import comes from?

https://github.com/thedirtyfew/dash-extensions/blob/bd7827b081f0164b1f6a4f05780edcd5e2cd196b/dash_extensions/_imports_.py#L10

**Comment by emilhe** [comment]
That line imports the Python code which is auto generated during the Dash component build process. Take a look at the docs for more details,

https://dash.plotly.com/plugins
