### ISSUE TITLE
Keyboard callback conflicting with other callbacks

### ISSUE THREAD

**Issue by guidocioni** [thedirtyfew/dash-extensions#22]
So I have a simple dash app where an image is generated based on a slider value. 

```python
@app.callback(
    Output('image_plt', 'src'),
    [Input('chart-dropdown', 'value'), Input('slider-step', 'value'), Input('proj-dropdown', 'value')])
def update_figure(chart, f_step, projection):
    return figure 
```

I want to be able to control the slider not only with the mouse but also with the keyboard by using the `LeftArrow` and `RightArrow` events to advance the slider. I wrote this simple function 

```python
@app.callback(Output(component_id='slider-step', component_property='value'), 
  [Input("keyboard", "keydown"), Input("slider-step", "value")])
def update_slider(event, slider_value):
  key_pressed = event['key']
  if key_pressed == "ArrowRight":
    if slider_value == max(steps):
      out = steps[0]
    else:
      out = slider_value + 1 
  elif key_pressed == "ArrowLeft":
    if slider_value == min(steps):
      out = steps[-1]
    else:
      out = slider_value - 1

  return out
```

which updates the `value` property of the slider depending on the `keydown` event. It also takes care of wrapping the next value if the end of the slider is reached. 

I thought this was going to work fine but when I insert this function in my app no image is produced and pressing the key doesn't update the slider BEFORE I interact with the mouse. Afterwards I'm able to change the value of the slider with my keys but the image is still not produced and for some reason I cannot go beyond the first and last element of the list (no wrapping). Any idea what I'm doing wrong?

**Comment by emilhe** [comment]
Have you tried preventing initial callbaks? Could you post an MWE that runs?

**Comment by guidocioni** [comment]
I've discovered something weird...even without including the `Keyboard` component the slider actually responds to Left and Right arrow key presses, so the behavior that I was seeing was not due to the use of `Keyboard`. 

Here is a code of a MWE https://github.com/guidocioni/cosmo_de_webapp and a live version that runs http://breeze.guidocioni.it/cosmo-de/. This is with the `Keyboard` callback part removed though!
