### ISSUE TITLE
Multipage App and MultiplexerTransform

### ISSUE THREAD

**Issue by JoGruen** [thedirtyfew/dash-extensions#224]
Hi, 

I  have a single page app and use MultiplexerTransform to target outputs by multiply callbacks, which works perfectly fine. Since I switched to multi page from dash 2.5.0 I get tons of errors about `Duplicate callback outputs`. Is this a current limitation or am I doing a mistake? 

Thanks in advance! 

Versions: 
dash 2.7.0
dash-extensions 0.1.7

**Comment by emilhe** [comment]
No, that should work. Could you post an MWE?

**Comment by JoGruen** [comment]
Thanks for your fast reply! The folder structure is as follows: 
```
- index.py
- content.py
- pages
    - first.py
```

The `content.py` file:
```
import dash
from dash import html
from .index import app

app.layout = html.Div(
    [
        dash.page_container
     ],
    style={"margin": "0", "height": "100%"}
)
```

The `index.py` file:
```
from dash_extensions.enrich import DashProxy, MultiplexerTransform
import flask


server = flask.Flask(__name__)

app = DashProxy(
    __name__,
    use_pages=True,
    suppress_callback_exceptions=True,
    transforms=[MultiplexerTransform()],
    server=server
)



if __name__ == "__main__":

    app.run_server(host='localhost', port=8000, debug=True)

```

and the `first.py`:
```
import dash
from dash import html
from dash_extensions.enrich import Input, Output
dash.register_page(__name__, path="/")


def layout():
return \
        html.Div(
            [
                html.P('How are you?', id='p'),
                html.Button('Press me', id='button-1'),
                html.Button('Press me', id='button-2')
            ],
            style={"margin": "0", "height": "100%"}
        )

@dash.callback(Output('p', 'children'),
               Input('button-1', 'n_clicks'))
def test1(n):
    return 'Hello world'

@dash.callback(Output('p', 'children'),
               Input('button-2', 'n_clicks'))
def test1(n):
    return 'Hello world1'
```

I assume the problem occurs since I use `@dash` instead of `@app` - could this be? If so, what is the proper way of doing it? 
Thanks!

**Comment by emilhe** [comment]
Yes, that is correct. You can't use the callback imported from dash, you should use the enrich equivalents. But it has always been that way 🙂, independent of versions.

**Comment by JoGruen** [comment]
Thank you! This helped a lot.
