### ISSUE TITLE
multiple callbacks - same output

### ISSUE THREAD

**Issue by avivazran** [thedirtyfew/dash-extensions#24]
in previous versions of this package, it was possible to write multiple callbacks to change the same output component (and also passing the triggering components value).
if I understand the README right, this is not possible anymore is it?

is there some way to achieve this functionality?

**Comment by emilhe** [comment]
Yes, the syntax just changed. Here is a small example,

https://github.com/thedirtyfew/dash-extensions/blob/master/examples/callback_group.py

**Comment by avivazran** [comment]
This doesn’t answer my question. What I meant is if it’s possible to **pass** the triggers argument to the callback **and** still use the multiple callbacks feature

**Comment by emilhe** [comment]
If you samt to pass the argument of the triggering component, you should use input, not trigger.

**Comment by avivazran** [comment]
Could you please take a look at this and explain to me why isn't it working?

```python

import dash_html_components as html
from dash_extensions.enrich import Output, Dash, Trigger, Input

button = html.Button("Click me", id="btn")
button2 = html.Button("Click me", id="btn2")
app = Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    button,
    button2,
    html.Div(id="log")
])

@app.callback(Output("log", "children"), Input("btn", "n_clicks"))
def func(N):  # argument is omitted from the function
    return "btn1"


@app.callback(Output("log", "children"), Input("btn2", "n_clicks"))
def func2(N):  # argument is omitted from the function
    return "btn2"


if __name__ == '__main__':
    app.run_server()
```

**Comment by emilhe** [comment]
You didn’t use the group keyword. It should be used as in the example i posted.
