### ISSUE TITLE
Manipulate excel file before using send_data_frame

### ISSUE THREAD

**Issue by sebastianbuechler** [thedirtyfew/dash-extensions#25]
I am using the send_data_frame functionality for providing a download data option which works perfectly with the example code provided in the documentation. 
`return send_data_frame(df.to_excel, filename='data.xlsx')`
However, what is the solution if I don't want to generate the excel within the function but before, so I can manipulate the excel file with the xlsxwriter like in these examples beforehand? https://xlsxwriter.readthedocs.io/working_with_pandas.html

In this case I need to generate the excel file first and then access it:
```
writer = pd.ExcelWriter('pandas_simple.xlsx', engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object.
df.to_excel(writer, sheet_name='Sheet1')

# Get the xlsxwriter objects from the dataframe writer object.
workbook  = writer.book
worksheet = writer.sheets['Sheet1']

# Apply a conditional format to the cell range.
worksheet.conditional_format('B2:B8', {'type': '3_color_scale'})

# Close the Pandas Excel writer and output the Excel file.
writer.save()
```

**Comment by emilhe** [comment]
Then you create a function that writes the data, here is an example,

https://stackoverflow.com/a/62088521/2428887

**Comment by sebastianbuechler** [comment]
@emilhe This is exactly what I was looking for. Thank you!
