### ISSUE TITLE
ServersideOutput is not working in deployment [SOLVED]

### ISSUE THREAD

**Issue by marcstern14** [thedirtyfew/dash-extensions#259]
I am running my plotly dash app on a private company server. When I decided to add the serverside output to pass large data around, it works great locally, but when I try to deploy it, I'm unable to pass around any kind of data, even just a test string. Any help would be appreciated

**Comment by mirix** [comment]
It may have something to do with this:

> The syntax of the ServersideOutputTransform has been changed. Instead of using ServersideOutput in place of the Output, one must now wrap return values in Serverside objects

Any examples of the new syntax?

**Comment by emilhe** [comment]
If the code works locally, but not deployed, it would indicate an issue with the deployment. What backend are you using? And how many instances are you running?
