### ISSUE TITLE
New release to match updates from Dash v2.9

### ISSUE THREAD

**Issue by connorferster** [thedirtyfew/dash-extensions#260]
Hi there!

I have been watching your recent commits and it seems like you are updating the code base to work with some of the new features in Dash v2.9. Looking forward to the new release! Do you have an ETA yet?

Very grateful for your work! Thank you!

**Comment by emilhe** [comment]
I have just released version 1.0.0, which builds on the latest Dash 2.9 features. Please try it out, and let me know if you have any issues :)

**Comment by florian6973** [comment]
Awesome! Does ServersideOutput will support allow_duplicate please?

**Comment by emilhe** [comment]
Yes, it does.
