### ISSUE TITLE
Serverside (v1.0.0) no longer works in the same way as previous ServersideOutput (v0.1.13)

### ISSUE THREAD

**Issue by matt-sd-watson** [thedirtyfew/dash-extensions#264]
I have recently upgraded the package from 0.1.13 to 1.0.0, and now the `Serverside` objects that are returned are throwing an error when previously, the `ServersideOutput` objects as dictionaries would function within the session. 

The error thrown is `returned a dictionary which is not JSON serializable`. Is there a way to upgrade to v1.0.0 but still retain the ability to return complex dictionaries as in v0.1.13?

**Comment by emilhe** [comment]
Have you tried version 1.0.1? Could you provide an small example demonstrating the issue?

**Comment by matt-sd-watson** [comment]
version 1.0.1 appears to work properly with the appropriate `FileSystemBackend`. Thanks!
