### ISSUE TITLE
FileSystemBackend keeps data in Memory instead of FileSystem

### ISSUE THREAD

**Issue by zariiii9003** [thedirtyfew/dash-extensions#268]
I create the cache with `cache_backend = FileSystemBackend(cache_dir=CACHE_DIR)` but i noticed, that the cache directory remains empty. Tracemalloc shows a high RAM usage of `cachelib`:
![image](https://github.com/thedirtyfew/dash-extensions/assets/52598363/354c8cfd-40b9-4c8c-982b-440be5e5ab2a)

I have the following versions installed:

```text
Python 3.10.11

dash                      2.10.2
dash-bootstrap-components 1.4.1
dash-core-components      2.0.0
dash-extensions           1.0.1
dash-html-components      2.0.0
dash-table                5.0.0

Flask-Caching             2.0.2
cachelib                  0.9.0
```

dash-extensions 0.1.13 worked fine for me.

**Comment by emilhe** [comment]
Could you post an MWE (i.e. a small piece of code that runs) demonstrating the issue?

**Comment by zariiii9003** [comment]
After a restart this did not happen anymore. I don't know why...
Closing for now, i'll reopen if it happens again.
