### ISSUE TITLE
ModuleNotFoundError: No module named 'BeforeAfter' 

### ISSUE THREAD

**Issue by labrunhosarodrigues** [thedirtyfew/dash-extensions#278]
Hello,

I am migrating a project that depends on dash-extensions from python3.7 to 3.10. While everything works correctly in 3.7, when I use an environment based on Python 3.10, the import of dash_extensions.enrich classes fails, with the error message:

`ModuleNotFoundError: No module named 'dash_extensions.BeforeAfter'`

I have tried building a fresh 3.10.7 environment and installing only dash-extensions, with the pip command, but when I try to import any module, the same error is produced.

This happens for version 1.0.2, which were the ones I tried.

I can make dash-extensions work with python 3.10 if I restrict the version to 0.1.11.

As far as I could see, the difference is that the installed package with version 1.0.2 is missing a series of Modules, of which BeforeAfter.py is one of them, which explains the error message.

With this said, the answer would be, why are the 1.0.2 version producing incomplete builds?

**Comment by labrunhosarodrigues** [comment]
I have reviewed the dist files of versions 1.0.2, 1.0.1 and 0.1.11, and the problem is that in fact 1.0.2 is the only one with the modules corresponding to the different dash components missing, maybe something broke during the packaging of this version, but at the moment 1.0.2 is not usable.

**Comment by emilhe** [comment]
How did you install `dash-extensions`?

**Comment by emilhe** [comment]
I have found the issue and published a new version 1.0.3, could you check it that one works on your side?

**Comment by nirajpandkar** [comment]
Works for Python 3.10 but doesn't work for 3.9 :(

**Comment by emilhe** [comment]
That makes sense - with the new CICD setup, the target version is now Python 3.10.

**Comment by labrunhosarodrigues** [comment]
Hi, I am using pipenv to manage my environments, so I am using `pipenv install dash-extensions`.
I have tested installing dash-extensions using python 3.10 and 3.9 and in both I can install it and import DashProxy without any problems.

(dash-extensions==1.0.3 was the version installed in both environments)

Thanks for the quick action!
