### ISSUE TITLE
thread/process safe caching

### ISSUE THREAD

**Issue by sdementen** [thedirtyfew/dash-extensions#28]
hello,

I wonder if the current memoize feature is thread & process safe ? ie if multiple inputs/triggers can start a callback that is expensive to run (in time), will the memoization make that only one calculation is done (when cache not initialised) vs multiple ones.

I just saw https://github.com/sjtrny/jitcache that could be a solution to make the memoize thread/process safe.

It is all suppositions as I haven't done the test (or dug into the code)

**Comment by emilhe** [comment]
The memorization feature utilizes flask-caching internally. Whether it's thread safe depends on the backup, i.e. if you use a `SimpleCache` (which is just a python dict) it's not thread safe. However, it does not include the prevent-repeated-computation feature.
