### ISSUE TITLE
Do grouped callbacks reduce the data transmission from client to server 

### ISSUE THREAD

**Issue by dominik-hayd** [thedirtyfew/dash-extensions#29]
I'm currently working on a dashboard, where selections and zooms in a graph should update the values of a dropdown.
At the moment I accomplish this with plain Dash with on callback that has the `'relayoutData'` and the `'selectData'` as Input and the figure as state.

In the callback I use dash.callback_context to determine which Input triggered the callback.
This method sends all data from the client to the server.
But obviously I only need one of the Inputs as only one can be updated at a time.
Additionally I only need the figure to access some of its data in one case. In the other only the Input data is sufficient.

I stumbled upon your extension while searching for a way to avoid the unnecessary data transmission.
But I'm not sure if your extension will solve my problem.
Did you tinkered with the frontend code to only send the required data?
Or do you 'just' use the callback context and pass on the selected data to the callback? In this case all data would be transmitted, right?

I would appreciate clarification on this.

**Comment by emilhe** [comment]
The group keyword is just syntactical sugar, i.e. all data are transmitted.

**Comment by dominik-hayd** [comment]
Thank you for the fast informantion

**Comment by emilhe** [comment]
Are you having performance issues since you were asking? (:

**Comment by dominik-hayd** [comment]
Sorry for the late reply.

I'm currently working on a prototype version of the dashboard and have not done any real performance tests yet.
It just came on my mind that this could be beneficial for the overall performance.
