### ISSUE TITLE
warm up cache

### ISSUE THREAD

**Issue by sdementen** [thedirtyfew/dash-extensions#30]
hello @emilhe ,

Is it possible to warm up the cache behind memoize at the start of the app ?
I would like to be able to call the function with different values of arguments so that at first use by the user the results are already there.

**Comment by emilhe** [comment]
I haven't tried it, but I see no reason why it shouldn't be possible. As you note, you would simply invoke the appropriate functions with the relevant arguments prior to launching the app. It could be in a separate script, or as part of the application launch script itself.

**Comment by sdementen** [comment]
So I have the app and the Flask server instantiated but I think that at that time the `apply` method hasn't been called yet. Should I trigger manually the method and if so how ? Otherwise, I guess the dash extension magic (with the memoize) has not yet been called and so my calls will have no effect, right ?
I have tried to call the callback before starting the server but with no apparent effect on the cache (the folder with the cached file is not filling up).
Before trying, I had to adapt https://github.com/thedirtyfew/dash-extensions/blob/master/dash_extensions/enrich.py#L63 to return the function f (instead of None)

**Comment by sdementen** [comment]
I will put the warm-up cache code in a callback on a static element so that it is trigged once when the app is sent to the client. It is going to slow down the first update of the app but will do it for now

**Comment by sdementen** [comment]
I close the issue as I do not see any simple way to do it. Feel free to reopen if you think it could be implemented in the future
