### ISSUE TITLE
app.clientside_callback not working ?

### ISSUE THREAD

**Issue by sdementen** [thedirtyfew/dash-extensions#31]
The example given in
https://community.plotly.com/t/ordering-children-with-drag-drop-how-to-trigger-dash-component-has-changed-from-js/47243 does not work when I replace the standard Dash with the one of dash-extensions.
I can't find exactly why it is not working properly... are the `clientside_callback` working with dash-extensions ?

**Comment by emilhe** [comment]
The `Dash` object of `dash-extensions` is a subclass of the original `Dash` object with only modifications of the `callback` decorator. Hence the `clientside_callback` function should works as normally. I just tried it out with a small example,

```
import dash_core_components as dcc
import dash_html_components as html
from dash_extensions.enrich import Dash, Input, Output

app = Dash(__name__)
app.layout = html.Div([dcc.Input(id="a"), html.Div(id="b")])
app.clientside_callback("function(x){return x};", Output("b", "children"), [Input("a", "value")])

if __name__ == '__main__':
    app.run_server()
```

and it works as intended. Note that mixing `dash-extensions` components with normal Dash components might cause issues.

**Comment by sdementen** [comment]
ok, i'll test again and will come back if the issue is still there
