### ISSUE TITLE
using Download for JPG/SVG etc files

### ISSUE THREAD

**Issue by TimChild** [thedirtyfew/dash-extensions#33]
Hi,
First, let me say that your extension looks great! And I am looking forward to using some more of the features soon!
I found your dash-extensions while looking for a way to allow a user to download files. It worked beautifully for an `html` file, but I am struggling to get a `jpg` file to both send and be openable. I am wondering if these is a fixed limitation due to the fact that the callbacks have to be jsonify-able or if I am just not understanding how to properly use your extension. 

This is roughly what I am trying to do:
```
@app.callback(Output(dl_id, 'data'), Input(fig_id, 'figure))  # dl_id is the 'id' of a Download component
def download_fig(fig):
    fig = go.Figure(fig_dict) 
    data = fig.to_image(format='jpg')
    data = base64.b64encode(data).decode()  # Copying what you do in sendbytes etc
    return dict(content=data, filename='test.jpg', mimetype='image/jpg', byte=True)
```

The file does download, and it recognized as a `jpg`, but fails to open, presumably because of the encoding. If I copy the contents of the downloaded file into a base64 converter, I see the image I am aiming for, but this is obviously not ideal...

Am I missing something? Or is this just a limitation imposed by how Dash works in general?

Thank you very much! 
Tim

**Comment by TimChild** [comment]
Ok, well I feel like a bit of an idiot to be replying to my own post soon soon... But I am still curious about what I was doing wrong above if you have time to answer and it's obvious to you without having to spend too much time on it! 

So I successfully sent a `jpg` file by saving it to a local file first, and then sending it with your `send_file`. Using:

```
fig.write_image('test.jpg', format='jpg')
return send_file('test.jpg', ....)
```

So I have answered my own question about whether there is an underlying limitation in Dash... clearly there isn't.  I guess I wasn't doing the base64 encoding correctly, and I don't understand that enough to know where I went wrong. 

Anyway, sorry for wasting your time reading all of this! 

Tim

**Comment by emilhe** [comment]
As you note yourself, there should be no limitations in `Dash` or the `Download` component. Your suggested approach of writing the file to disk is perfectly valid, but you can also send the bytes directly if you prefer,

```
import dash
import dash_html_components as html
import plotly.graph_objects as go
from dash.dependencies import Input, Output
from dash_extensions import Download
from dash_extensions.snippets import send_bytes

app = dash.Dash()
app.layout = html.Div([html.Button("Download", id="btn"), Download(id="download")])


@app.callback(Output("download", "data"), [Input("btn", "n_clicks")])
def download(n_clicks):
    f = go.Figure()
    return send_bytes(f.write_image, "figure.png")


if __name__ == '__main__':
    app.run_server()

```

**Comment by BrendanJM** [comment]
@emilhe Great solutions, this thread was super helpful. I might recommend considering putting something like this in the readme, as this was one of my first questions when I discovered this library.

**Comment by emilhe** [comment]
Thanks! I have added a few examples to the documentation :)
