### ISSUE TITLE
0.0.33 has bug on enrich module

### ISSUE THREAD

**Issue by sylvoslee** [thedirtyfew/dash-extensions#34]
but i don't know why,so return to 0.0.31

**Comment by sylvoslee** [comment]
but i don't know why,so return to 0.0.31, and get some error like this
`\lib\site-packages\dash_extensions\enrich.py", line 338, in decorated_function
    args[i] = serverside_output.backend.get(args[i], ignore_expired=True)
IndexError: list index out of range`

**Comment by emilhe** [comment]
What is the bug?

**Comment by sylvoslee** [comment]
Input seems to be invalid and cannot trigger callback

**Comment by emilhe** [comment]
Could you test again with 0.0.37? And if you still see an error, could you post the code?

**Comment by sylvoslee** [comment]
The bug is on group,code like below,search1 can trigger the callback,but search2 can not
`@app.callback(
    [
        Output('table','data'),
        Output('query-table','dropdown_data'),
    ],
    [
        Input('search1','n_clicks'),
        Input('search2', 'n_clicks'),
    ],
    [
        State('table','data')
    ],
    group='group3'
    )

def test1(n1,n2):
    pass

@app.callback(
    Output('table','data'),
    [
        Input('search3','n_clicks'),
    ],
    group='group3'
    )

def test2(n1):
    pass`

**Comment by emilhe** [comment]
Ah, yes, i think i found the bug. Can you test if it's fixed in the 0.0.38rc1 release?

https://pypi.org/project/dash-extensions/0.0.38rc1/

**Comment by sylvoslee** [comment]
yes, it is fixed,thank you very much

**Comment by sylvoslee** [comment]
another issue， It seems that it cannot wait until the previous callback is completed

`@app.callback(
    ServersideOutput("search_result", "data"),
    [
        Input('search','n_clicks'),
        ],
    group='grp-search'
    )
def keywords_search(n1):
    pass

@app.callback(
    ServersideOutput("search_result", "data"),
    [
        Input('dash-uploader', 'isCompleted'),
        ],
    group='grp-search'
    )
def file_search(upload_file):
    pass

@app.callback(
    Output('query-table','data'),
    [
        Input("search_result", "data"),
    ],
)
def table_data(df):
    pass`

**Comment by emilhe** [comment]
I am not sure what the question is. Could you elaborate? And/or post a runnable MWE?

**Comment by sylvoslee** [comment]
![image](https://user-images.githubusercontent.com/34852097/102422893-b1cdb600-4042-11eb-8595-797b0609315f.png)

**Comment by sylvoslee** [comment]
![image](https://user-images.githubusercontent.com/34852097/102424088-649f1380-4045-11eb-8cd2-f4193ecafe1f.png)
