### ISSUE TITLE
0.0.39 bug

### ISSUE THREAD

**Issue by sylvoslee** [thedirtyfew/dash-extensions#38]
![bug](https://user-images.githubusercontent.com/34852097/103324223-81920880-4a81-11eb-8724-709bc62a7ded.jpg)

**Comment by emilhe** [comment]
Creating a virtual environment from scratch, it works fine on my laptop (Linux Mint), so I suspect it's a Windows-only error. Maybe it could be caused by lack of case sensitivity (i have both a file names websocket.py and WebSocket.py)? I have tried renaming the former in this build,

https://pypi.org/project/dash-extensions/0.0.40rc1/

**Comment by paul-rs** [comment]
> Creating a virtual environment from scratch, it works fine on my laptop (Linux Mint), so I suspect it's a Windows-only error. Maybe it could be caused by lack of case sensitivity (i have both a file names websocket.py and WebSocket.py)? I have tried renaming the former in this build,
> 
> https://pypi.org/project/dash-extensions/0.0.40rc1/

Just confirming that I'm getting the same error in Windows on version 0.0.39 and that version 0.0.40rc1 fixes it

**Comment by ebrangwin** [comment]
> > Creating a virtual environment from scratch, it works fine on my laptop (Linux Mint), so I suspect it's a Windows-only error. Maybe it could be caused by lack of case sensitivity (i have both a file names websocket.py and WebSocket.py)? I have tried renaming the former in this build,
> > https://pypi.org/project/dash-extensions/0.0.40rc1/
> 
> Just confirming that I'm getting the same error in Windows on version 0.0.39 and that version 0.0.40rc1 fixes it

Same here (on Windows)

**Comment by emilhe** [comment]
I have pushed a new version 0.0.40 with the fix,

https://pypi.org/project/dash-extensions/0.0.40/

Please let me know if it now works on Windows. If so, i guess this issue can be closed :)

**Comment by paul-rs** [comment]
> I have pushed a new version 0.0.40 with the fix,
> 
> https://pypi.org/project/dash-extensions/0.0.40/
> 
> Please let me know if it now works on Windows. If so, i guess this issue can be closed :)

Thanks for the quick fix! Tested in Windows and 0.0.40 resolves the issue for me.

**Comment by ebrangwin** [comment]
> > I have pushed a new version 0.0.40 with the fix,
> > https://pypi.org/project/dash-extensions/0.0.40/
> > Please let me know if it now works on Windows. If so, i guess this issue can be closed :)
> 
> Thanks for the quick fix! Tested in Windows and 0.0.40 resolves the issue for me.

Thanks! this also works for me.
