### ISSUE TITLE
CallbackBlueprint error appers in versions 0.024

### ISSUE THREAD

**Issue by ThomasRippon** [thedirtyfew/dash-extensions#4]
when importing
from dash_extensions.callback import CallbackGrouper
error 
    class CallbackCache(CallbackBlueprint):
NameError: name 'CallbackBlueprint' is not defined

**Comment by emilhe** [comment]
It seems that i made a mistake in the (0.0.24). Do you need the keyboard component? Otherwise, i guess you could just downgrade to 0.0.23 for now. I expect to release a new build this week.

**Comment by emilhe** [comment]
I have now pushed version (0.0.26) with the new syntax.
