### ISSUE TITLE
Hitting error with normal Output and memoize=True

### ISSUE THREAD

**Issue by godotgildor** [thedirtyfew/dash-extensions#44]
Hi, thanks for putting together this package - the serverside caching is exactly what I was looking for and it looks pretty easy to use.

In trying to adapt my code, I'm running into an error when I try to memoize a callback that is using just a normal output and not a serverside output. With that configuration, I hit an error on the following line as `output` does not have an attribute called `backend`. Is the use of normal outputs and memoize=True not supported?

https://github.com/thedirtyfew/dash-extensions/blob/6c530cd47667d06c856f28c4466179e639fbb6fa/dash_extensions/enrich.py#L407

To recreate, one can take the `callback_serverside_output.py` example file and just add `memoize=True` to the callback decorator of the `update_dd` function, like so:
```
@app.callback(Input("store", "data"), Output("dd", "options"), memoize=True)
def update_dd(df):
    return [{"label": column, "value": column} for column in df["year"]]
```

**Comment by emilhe** [comment]
Ah, yes. To use that option, you would probably need to switch to an `EnrichedOutput`. I should probably add that to the docs :)

**Comment by godotgildor** [comment]
Great - thanks for the pointer - I'll give that a try.

**Comment by ManuDiehn** [comment]
Hi,

Was issue resolved? I'm getting the same error - even when I use EnrichedOutput.

Thanks
