### ISSUE TITLE
Monitor probes do not support dict IDs

### ISSUE THREAD

**Issue by Yook74** [thedirtyfew/dash-extensions#45]
The Monitor component's `probes` attribute [expects string IDs.](https://github.com/thedirtyfew/dash-extensions/blob/48b790e71b0e302837850a2e4395b9910b6f841f/src/lib/components/Monitor.react.js#L116)

It would be great if this could be updated to work with dictionary IDs as well.

**Comment by emilhe** [comment]
Ah, yes, that's true. I never god around to that part ;). The problem that the component was originally developed to solve, has been partially addressed in the most [recent version of Dash](https://community.plotly.com/t/dash-1-19-0-circular-callbacks-drag-value-in-dcc-slider-close-button-in-dev-tools-dcc-graph-bug-fixes/49500) via the circular callback feature. Maybe it suits your use case?

Thanks for the pull request! I hope to get the time to go through it in the weekend :)

**Comment by emilhe** [comment]
I have now merged the pull request (nice, short, and concise) and published a [new version](https://pypi.org/project/dash-extensions/0.0.45/) with the changes.
