### ISSUE TITLE
[Trigger] Allow to raise PreventUpdate on None values

### ISSUE THREAD

**Issue by gv-collibris** [thedirtyfew/dash-extensions#48]
Hi,
The main use I have for `Trigger` is for handling buttons.
However, my callbacks are triggered on load, as the `n_clicks` property sends a `None` value to the callback when a button is created.
Is there a way to use `Trigger` instead of `Input` and raise a `PreventUpdate` exception if the value sent by `Trigger` is `None` ?
I have no use of the actual number of clicks on the button, I just need to know when it's clicked on.

**Comment by emilhe** [comment]
I have decided to discontinue the `Trigger` component for now.
