### ISSUE TITLE
A websocket example connecting to socket IO python server?

### ISSUE THREAD

**Issue by DaneGrinder** [thedirtyfew/dash-extensions#49]
Sorry to ask a question here cause this is not an issue with the dash-extensions, it is simply me not knowing websockets etc well enough to use it.

I'm simply just trying to write a socketIO server running on gunicorn (uvicorn for async) and have the websocket from dash-extensions connect to it?

```
WebSocket connection to 'ws://localhost:8000/' failed: Error during WebSocket handshake: Unexpected response code: 404
value @ WebSocket.react.js:14
```
server code
```
import socketio

sio = socketio.Server()
app = socketio.WSGIApp(sio)

@sio.event()
def connect(sid, environ, auth):
    print('connect ', sid)
    # Refuse client connections
    if False:
        raise ConnectionRefusedError('authentication failed')

@sio.event
def disconnect(sid):
    print('disconnect ', sid)


if __name__ == '__main__':
    app.run_server()
```

client side is just the example code
```
import dash_core_components as dcc
import dash_html_components as html
import dash_extensions as de
from dash import Dash
from dash.dependencies import Input, Output

# Create example app.
app = Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    dcc.Input(
        id="input", autoComplete="off"
        ),
    html.Div(id="msg"),
    de.WebSocket(url="ws://localhost:8000/", id="ws")
])
# Send input value using websocket.
send = "function(value){return value;}"
app.clientside_callback(            
            send,
            Output("ws", "send"),
            [Input("input", "value")],
        )
# Update div using websocket.
receive = "function(msg){console.log(msg.data); return \"Response from websocket: \" + msg.data;}"
app.clientside_callback(
            receive,
            Output("msg", "children"),
            [Input("ws", "message")]
        )

if __name__ == '__main__':
    app.run_server()
```

**Comment by emilhe** [comment]
Did you look at the examples? E.g.

https://github.com/thedirtyfew/dash-extensions/blob/master/examples/websocket_push.py

**Comment by DaneGrinder** [comment]
Thank you for taking time to help me here.

Yes, I have been through it all over and over again and at this point I am just getting more and more confused :-)

I just wanted to use the standard python socketIO because I was thinking that a websocket is a websocket is a websocket :-) But at this point I'm okay with just going with the flask socketIO implementation for now, if that can get me moving forward again, so I'll go ahead and switch to that tomorrow and I will let you know how that goes.

**Comment by DaneGrinder** [comment]
I got a little further here :-) But unfortunately I'm to stupid to understand what to do with the code you linked too?¿?¿
Tried to run the code from the first link and add the code from the second link in the assets folder. No errors but also no output other than an empty Div with the id="msg"

I now have the flask socketIO server running and when the client connects I do not get any errors on either side and it does get the 101 websocket connection on the client, but there is still no communication between them. The server even seems to accept the connection without calling the 'client_connected' function and it doesn't print anything to the terminal.

Server running on localhost/5000
```
from flask import Flask, render_template
from flask_socketio import SocketIO, send, emit


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@socketio.on('connect')
def client_connected():
    print('Client connected')
    send('You have connected')

@socketio.on('message')
def client_msg(msg):
    print(f'Client msg: {msg}')

if __name__ == '__main__':
    socketio.run(app, debug=True)
```
Client running on localhost:8050
```
import dash_core_components as dcc
import dash_html_components as html
import dash_extensions as de
from dash import Dash
from dash.dependencies import Input, Output

# Create example app.
app = Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    dcc.Input(
        id="input", autoComplete="off"
        ),
    html.Div(id="msg"),
    de.WebSocket(url="ws://localhost:5000/", id="ws")
])
# Send input value using websocket.
send = "function(value){return value;}"
app.clientside_callback(            
            send,
            Output("ws", "send"),
            [Input("input", "value")],
        )
# Update div using websocket.
receive = "function(msg){console.log(msg.data); return \"Response from websocket: \" + msg.data;}"
app.clientside_callback(
            receive,
            Output("msg", "children"),
            [Input("ws", "message")]
        )

if __name__ == '__main__':
    app.run_server()
```
Again, I am really sorry for bothering you with something this trivial, but for me just doesn't compute.

**Comment by DaneGrinder** [comment]
I'm getting the impression that you are trying to help me out both here and on the Dash forum?

**Comment by emilhe** [comment]
Haha, yes, it is me in both places. I was also wondering if you were the same ;)

**Comment by emilhe** [comment]
I think the issue is beyond the scope of this project (it's not really related to the `WebSocket` component, but rather to the server side setup). Try on the Dash forum or on SO.
