### ISSUE TITLE
Dash Bootstrap Components Tooltip and Multipage App Extension

### ISSUE THREAD

**Issue by demattia** [thedirtyfew/dash-extensions#52]
### Use Case
Development of multipage apps where the individual pages include tooltips from the Dash Bootstrap Components package.

### Problem Description
The Dash Bootstrap Tooltip component (https://dash-bootstrap-components.opensource.faculty.ai/docs/components/tooltip/)) utilizes a "target" keyword argument to specify the id of its target component. Component ids are mutated by the multipage app. However, the target is not updated and this breaks the tooltip.

### Desired Behavior
The tooltip target is updated to match the id.

**Comment by emilhe** [comment]
I have just release a version 0.0.52, which adds the requested feature. If you have any problems, please reopen this issue and post a MWE demonstration the problem.
