### ISSUE TITLE
Not serializable error for ServersideOutput

### ISSUE THREAD

**Issue by Mahdi-Hosseinali** [thedirtyfew/dash-extensions#56]
I have a function that receives input from two different sources, picks one of them, and then passes it to two outputs. 

```
@app.callback(
    ServersideOutput('interface-state', 'data'),
    ServersideOutput('tag-table-input', 'data'),
    Input('data-source-state', 'modified_timestamp'),
    Input('flight-analyze-state', 'modified_timestamp'),
    State('data-source-state', 'data'),
    State('flight-analyze-state', 'data'),
)
def data_funnel(data_src_t, flight_t, data_src, flight):
    return data_src if data_src_t > flight_t else flight
```

Both inputs receive dictionaries with an object as a value that is not serializable. When the same object is passed from `data-source-state`, the output of this function complains about the object not being serializable. When it comes from `flight-analyze-state` it passes through without a problem! I pickle the object and pass a serializable value to the input then load the object and it works fine. Very confused about what is going on.

Here's the error:

> Traceback (most recent call last):
>   File "C:\Users\MahdiHosseinali\miniconda3\envs\data\Lib\site-packages\dash_extensions\enrich.py", line 604, in decorated_function
>     unique_id = _get_cache_id(f, output, list(filtered_args), output.session_check)
>   File "C:\Users\MahdiHosseinali\miniconda3\envs\data\Lib\site-packages\dash_extensions\enrich.py", line 620, in _get_cache_id
>     return hashlib.md5(json.dumps(all_args).encode()).hexdigest()
>   File "C:\Users\MahdiHosseinali\miniconda3\envs\data\Lib\json\__init__.py", line 231, in dumps
>     return _default_encoder.encode(obj)
>   File "C:\Users\MahdiHosseinali\miniconda3\envs\data\Lib\json\encoder.py", line 199, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "C:\Users\MahdiHosseinali\miniconda3\envs\data\Lib\json\encoder.py", line 257, in iterencode
>     return _iterencode(o, 0)
>   File "C:\Users\MahdiHosseinali\miniconda3\envs\data\Lib\json\encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type rootDirectory is not JSON serializable

**Comment by emilhe** [comment]
Hmm, that sounds weird. Are you able to make a small MWE that reproduces the error? Then I'll take a look at what is going on :)

**Comment by emilhe** [comment]
I will close this issue for now. Please reopen and post an MWE if you still have issues on the latest release.

**Comment by Mahdi-Hosseinali** [comment]
After updating to the latest version and a little change in my data-flow I didn't get the error anymore.
