### ISSUE TITLE
MultiplexerTransform Seems to not play well with dbc.Collapse

### ISSUE THREAD

**Issue by mwang87** [thedirtyfew/dash-extensions#60]
on dash 1.19.0, when enabling MultiplexerTransform sometimes seems to not hide dbc.Collapse.

**Comment by emilhe** [comment]
Could you post an mwe?

**Comment by emilhe** [comment]
I have just release a version 0.0.52, which makes it possible to use custom proxy wrapper components. I believe this might be a way to mitigate this issue. If not, please reopen this issue and post a MWE demonstration the problem(s) that you are experiencing.
