### ISSUE TITLE
MultiplexerTransform does not work with clientside callback

### ISSUE THREAD

**Issue by agvdndor** [thedirtyfew/dash-extensions#61]
Hi, first of all a big thanks for your work!

I tried the MultiplexerTransform which does not seem to work when clientside callbacks are involved. Is this expected behavior?

I adapted the provided sample to a mwe:

```
import dash_html_components as html
from dash_extensions.enrich import Output, DashProxy, Input, MultiplexerTransform

app = DashProxy(prevent_initial_callbacks=True, transforms=[MultiplexerTransform()])
app.layout = html.Div([html.Button("left", id="left"), html.Button("right", id="right"), html.Div(id="log")])


@app.callback(Output("log", "children"), Input("left", "n_clicks"))
def left(_):
    return "left"


app.clientside_callback(
    """
    function(n_clicks){
        return "right";
    }
    """,
    Output("log", "children"),
    Input("right", "n_clicks")
)



if __name__ == '__main__':
    app.run_server(debug=True, port=7777)
```

**Comment by emilhe** [comment]
Thanks! I just added clientside support, but I haven’t released it yet. You can try it here,

pip install dash-extensions==0.0.52rc1

**Comment by emilhe** [comment]
I have just release a version 0.0.52, which adds the requested feature. If you have any problems, please reopen this issue and post a MWE demonstration the problem.
