### ISSUE TITLE
Use existing flask_caching redis instance in place of FileSystemStore

### ISSUE THREAD

**Issue by slochower** [thedirtyfew/dash-extensions#63]
Hi, thanks for the super useful extensions, especially the `ServersideOutput` callback.

I noticed that, by default, `dash-extensions` is using a `FileSystemStore` for memoization and I've seen that you can change the path that based on your comments here: https://community.plotly.com/t/show-and-tell-server-side-caching/42854/18

The rest of my app is using `redis` as cache by setting it up through `flask_caching`:

```
from flask_caching import Cache
import os
from app import app


CACHE_CONFIG = {
    "CACHE_TYPE": "redis",
    "CACHE_REDIS_URL": os.environ.get("REDIS_URL", "redis://localhost:6379"),
}

cache = Cache()
cache.init_app(app.server, config=CACHE_CONFIG)
```

Since `dash-extensions` is _also_ using `flask_caching`, is there a way I can get rid of `FileSystemStore` and use `redis` directly?

**Comment by slochower** [comment]
Edit: After reading all the way to your most recent post (oops), would it be conceivable to add a class along these lines?

```python

from flask_caching import RedisCache

class RedisStore(RedisCache):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def get(self, key, ignore_expired=False):
        if not ignore_expired:
            return super().get(key)

        # Is there an analog of `_get_filename` for RedisCache?

        # TODO: This part must be implemented for each type of cache.
        # filename = self._get_filename(key)
        # try:
        #     with open(filename, "rb") as f:
        #         pickle_time = pickle.load(f)  # ignore time
        #         return pickle.load(f)
        # except (IOError, OSError, pickle.PickleError):
        #     return None
```

If so, I'd be happy to try a PR.

**Comment by emilhe** [comment]
I have added an (experimental) implementation in version 0.0.53, and it seems to work. The only pitfall that i am aware of is that the Dash app will crash if a (k,v) pair expires in the Redis cache. Hence you should either set the timeout to 0 (inf), or at least higher that you would ever expect a user to be connected to your app. Let me know how it goes :)

```
app = DashProxy(transforms=[ServersideOutputTransform(backend=RedisStore())])
```

**Comment by slochower** [comment]
Sweet! This appears to be working flawlessly. I simply changed the `FileSystemStore` to `RedisStore` and didn't make any other changes.
