### ISSUE TITLE
Enhancement: make keyboard capture multiple keys

### ISSUE THREAD

**Issue by JonThom** [thedirtyfew/dash-extensions#64]
Hi,

Thanks so much for these excellent extensions - really valuable for my work building an app!

For the keyboard component, it would be useful to be able to use combinations of keydowns (e.g. Ctr + a  + l). 
An easy solution seems to be to use an array of boolean values, which are reset to `false` on keyup. 
See https://www.gavsblog.com/blog/detect-single-and-multiple-keypress-events-javascript

(happy to have a go at a PR, too)

**Comment by emilhe** [comment]
Thanks! I have just added keyup, n_keyups and keys_pressed props. You can try them out in verion 0.0.53, let me know if it solves your usecase.

**Comment by JonThom** [comment]
I think that more than solves my use case. Great stuff!
