### ISSUE TITLE
how to get started?

### ISSUE THREAD

**Issue by tstorek** [thedirtyfew/dash-extensions#67]
Hello,

thanks, for providing the library. Especially, the multipage approach looks useful to me.
I had something similar in the past, but not as clean as this one.

Nevertheless, I cannot manage to run the examples. I think that the imports are somehow not correct.

Things, I tried:

1. Clone the repo and run the examples directly in pycharm only installing the requirements
2. Install dash-extensions and run the examples in pycharm

Either way, I do not manage to have imports working. 
Could it be that this was never tested?

Otherwise, please elaborate how to start using the library or run the examples :)

Thanks in advance!

**Comment by emilhe** [comment]
Hi Thomas,

Thanks! Which example are you referring to?

Typically when i test the examples, I would

* Create a new project (e.g. in pycharm) with a clean venv
* Install dash-extensions (and other packages needed)
* Copy the relevant example file(s) into the project and run them

I haven't set up automated testing of the example, so it is not impossible
that I might have made some mistakes along the way.

\emher

**Comment by tstorek** [comment]
I tried the multipage example. Only very quickly in order to decide if I would like to refactor my former standard multi-page approach. What happens actually in the code is that there several imports that actually should be relative imports. Others should be relative import but are absolute imports.

Especially, I wanted to answer the questions of how the location of the pages will be created and if it is also possible to pass args via the url for instance.

**Comment by frnhr** [comment]
Same issue here. Import from `_imports.py` seems to be at fault. For example, grepping the repo for `BeforeAfter` gives no meaning full code. 

Never mind PyCharm, just running an example directly from shell gives this error:
``` python
$ python examples/callback_no_ouput.py 
Traceback (most recent call last):
  File "examples/callback_no_ouput.py", line 2, in <module>
    from dash_extensions.enrich import Dash, Input
  File "/Volumes/Projects/contrib/dash-extensions/dash_extensions/__init__.py", line 11, in <module>
    from ._imports_ import *
  File "/Volumes/Projects/contrib/dash-extensions/dash_extensions/_imports_.py", line 1, in <module>
    from .BeforeAfter import BeforeAfter
ModuleNotFoundError: No module named 'dash_extensions.BeforeAfter'

```

Same when trying to import `django_extensions` from python shell:

``` python
Python 3.8.10 (default, Jun 13 2021, 15:31:30) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dash_extensions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Projects/contrib/dash-extensions/dash_extensions/__init__.py", line 11, in <module>
    from ._imports_ import *
  File "/Volumes/Projects/contrib/dash-extensions/dash_extensions/_imports_.py", line 1, in <module>
    from .BeforeAfter import BeforeAfter
ModuleNotFoundError: No module named 'dash_extensions.BeforeAfter'

```

**Comment by frnhr** [comment]
Had no luck running `npm run start`, but `npm run build` seems to do the trick. But I have no idea what I'm doing here... Should I be using npm or something else? Some basic getting started docs would definitely be appreciated. 

The whole project is already very much appreciated, though! 😃

**Comment by emilhe** [comment]
Unless you want to do development, you don't need npm. You can just install the library from pip,

```
pip install dash-extensions dash-bootstrap-components
```

If you then download the examples folder, you should be able to run the examples like this,

```
python -m examples.multipage_app
```

Note however that if you clone the repo, you must either build dash_extensions before running the example, or copy the examples folder elsewhere.

**Comment by frnhr** [comment]
Yeah, I believe the OP (and also I) was talking about running the included examples, which means running the build first. A few lines of instructions in the readme about how to build for development would be great.

Speaking from my perspective, being primarily a Python dev, I start to hyperventilate when I see `package.json` 🤪 Probably am not alone in this.

**Comment by emilhe** [comment]
Haha, me too. Did you get it working?

**Comment by MattMacs** [comment]
took me some time, too
but finally... made a virtual environment where  I installed dash-extensions, copied multi_page.app and the examples/pages folder to another directory and it worked

**Comment by mayurpande** [comment]
I tried to create a new project in Pycharm for the websockets (long callback) example. I installed the following packages:

```
bidict==0.21.4
Brotli==1.0.9
cffi==1.15.0
click==8.0.4
colorama==0.4.4
dash==2.2.0
dash-bootstrap-components==1.0.3
dash-core-components==2.0.0
dash-extensions==0.0.71
dash-html-components==2.0.0
dash-table==5.0.0
EditorConfig==0.12.3
Flask==2.0.3
Flask-Caching==1.10.1
Jinja2==3.0.3
jsbeautifier==1.14.0
MarkupSafe==2.1.0
more-itertools==8.12.0
plotly==5.6.0
pycparser==2.21
python-engineio==4.3.1
python-socketio==5.5.2
six==1.16.0
tenacity==8.0.1
Werkzeug==2.0.3
zope.event==4.5.0
zope.interface==5.4.0

```
However each time I try to run it nothing happens.

**Comment by mayurpande** [comment]
Thanks, will this be able to handle long callbacks on a server?

**Comment by emilhe** [comment]
On the websocket server, yes. Not on the Dash server (unless they are the same of course). Another option is to use Celery. The right choice depends on the use case.

**Comment by emilhe** [comment]
Closed due to inactivity.
