### ISSUE TITLE
WebSocket does not work when running the server with debug=True

### ISSUE THREAD

**Issue by GabGett** [thedirtyfew/dash-extensions#68]
Hello, I am getting this error when I enable the debug flag with app.run_server(debug=True)

Invalid argument `send` passed into WebSocket with ID "ws".
Expected `object`.
Was supplied type `string`.

However it works fine if I run it without the flag : app.run_server()

**Comment by emilhe** [comment]
Could you post/link to a piece of example code?

**Comment by GabGett** [comment]
Sure.

`
import dash_core_components as dcc
import dash_html_components as html

from dash import Dash
from dash.dependencies import Input, Output
from dash_extensions import WebSocket

# Create example app.
app = Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    dcc.Input(id="input", autoComplete="off"), html.Div(id="message"),
    WebSocket(url="wss://echo.websocket.org", id="ws")
])

# Write to websocket.
@app.callback(Output("ws", "send"), [Input("input", "value")])
def send(value):
    return value

# Read from websocket.
@app.callback(Output("message", "children"), [Input("ws", "message")])
def message(message):
    return f"Response from websocket: {message['data']}"  # read from websocket

if __name__ == '__main__':
    app.run_server(debug=True) #does not work
    # app.run_server() #works
`

pip freeze | grep dash

`
dash==1.20.0
dash-core-components==1.16.0
dash-extensions==0.0.53
dash-html-components==1.1.3
`

**Comment by emilhe** [comment]
Ah, yes. I can see that I made the type check too agressive; it allows only dicts, but in the example a simple string is used. Both will work, but since the type checker only expects dict, you will see an error in debug mode. I'll relax the type check in the next version.

**Comment by GabGett** [comment]
Alright, thank you for the explanation! Cheers

**Comment by emilhe** [comment]
Should be fixed in 0.0.55
