### ISSUE TITLE
Is there a way to save json files via the Download function?

### ISSUE THREAD

**Issue by ShramanaT** [thedirtyfew/dash-extensions#72]
I would like to store some http responses as .json files. I am able to save .txt files. Is there a way to easily save .json files?

**Comment by emilhe** [comment]
Please post questions on SO and bug reports there :). That being said, that should be possible - and simple. You can either send the data directly (in-memory) or save the data to disk first depending on your preferences.

**Comment by ShramanaT** [comment]
Alright, I will! :) I can save it easily with the json.dump() method. Was curious if it could be achieved through the Download function of this library, since I could not find any examples.
