### ISSUE TITLE
flask_login

### ISSUE THREAD

**Issue by linqingfan** [thedirtyfew/dash-extensions#75]
Hi,
Thanks for the excellent work.
I tried to use flask_login on dash_extension and I have these errors:

code:

server = Flask(__name__)
app = Dash(__name__, server=server)
login_manager=LoginManager()
login_manager.init_app(app)

error:

Traceback (most recent call last):
  File "index.py", line 26, in <module>
    login_manager.init_app(app)
  File "/usr/local/lib/python3.6/site-packages/flask_login/login_manager.py", line 117, in init_app
    app.after_request(self._update_remember_cookie)
AttributeError: 'Dash' object has no attribute 'after_request'

May I know what could have been the problem?

**Comment by emilhe** [comment]
Where do you see that it is a dash-extensions error?

**Comment by linqingfan** [comment]
It seems to me flask login manager cannot be use when using dash_extensions.

**Comment by emilhe** [comment]
I am not sure I understand what is going on. Could you post an MWE that works with vanilla Dash, but not with dash-extensions?

**Comment by emilhe** [comment]
Closed due to inactivity.
