### ISSUE TITLE
ServersideOutput stop working when used with dash-keycloak

### ISSUE THREAD

**Issue by nicksi** [thedirtyfew/dash-extensions#78]
There is no errors in the log/console/etc, but values are not saved in the store at all. Switching back to "plain" Output make bug disappear

dash-extensions 0.0.55
dash-keycloak 0.0.23

**Comment by emilhe** [comment]
Could you post a MWE demonstrating the issue?

**Comment by emilhe** [comment]
Closed due to inactivity.
