### ISSUE TITLE
Dash-Extensions duplicate callback output errors on subsequent tests when running from __main__.py

### ISSUE THREAD

**Issue by andrewwardcap** [thedirtyfew/dash-extensions#79]
OS: Windows 10
Python: 3.7.10
Dash:

	  dash==1.19.0
	  dash-bootstrap-components==0.12.2
	  dash-core-components==1.15.0
	  dash-extensions==0.0.55
	  dash-html-components==1.1.2
	  dash-renderer==1.9.0
	  dash-table==4.11.2

I'm using Pytest and Selenium to write UI tests.

The attached source code is a minimal reproducible example, and contains two Python projects:

- Dash1: Dash-Extensions app with selenium tests
- Dash2: Same app, but with Dash only

Reproduction

* Install [Chrome](https://www.google.com/chrome/)
* Install [Chromedriver](https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_win32.zip):
	* Extract the .zip somewhere
	* Update the PATH environment variable to include the folder containing the chromedriver(.exe)
* Run `pytest dash2`, see that all tests pass.
* Run `pytest dash1` and see that the second test, despite being exactly the same, will fail with the following console error:

  ```json
  {
      "message": "Duplicate callback outputs",
      "html": "In the callback for output(s):\n  my-output.value\nOutput 0 (my-output.value) is already in use.\nAny given output can only have one callback that sets it.\nTo resolve this situation, try combining these into\none callback function, distinguishing the trigger\nby using `dash.callback_context` if necessary."
  }
  ```

  This error appears whether or not `MultiplexerTransform` is enabled.

* Uncomment the `# app_file = "dash1.app"` line in `dash1/test_app.py`. This will change `import_app("dash1")` to `import_app("dash1.app")`. Both tests will now pass.

However, this workaround has an issue: in my actual production app, `import_app("dash1.app")` prevents all callbacks from running in the UI tests with no displayed errors, with or without dash-extensions. I've not been able to reproduce this in the minimal example yet.

[mre.zip](https://github.com/thedirtyfew/dash-extensions/files/6638156/mre.zip)

**Comment by RafaelWO** [comment]
I have the same issue: My tests don't pass when using duplicate `Output`s with `MultiplexerTransform`.

**Comment by emilhe** [comment]
@RafaelWO Could you post a MWE?

**Comment by RafaelWO** [comment]
Sure: [dash_mp_example.zip](https://github.com/thedirtyfew/dash-extensions/files/8242462/dash_mp_example.zip)

My setup:
```
python                    3.8.8
dash                      2.0.0
dash-bootstrap-components 1.0.1rc3
dash-extensions           0.0.71
```

Running `pytest` results in the following
```
❯ pytest test_dash_mp.py
Test session starts (platform: linux, Python 3.8.8, pytest 7.0.1, pytest-sugar 0.9.4)
plugins: Faker-6.6.0, flaky-3.7.0, sugar-0.9.4, requests-mock-1.9.3, dash-2.0.0, cov-3.0.0, anyio-3.3.4
collecting ... 
 test_dash_mp.py ✓                                                                         50% █████     

―――――――――――――――――――――――――――――――――――――――――――――― test_click ―――――――――――――――――――――――――――――――――――――――――――――――

dash_duo = <dash.testing.composite.DashComposite object at 0x7f22a3419a90>
dash_app = <dash_extensions.enrich.DashProxy object at 0x7f22a91dba90>

    def test_click(dash_duo, dash_app):
        dash_duo.start_server(dash_app)
        dash_duo.wait_for_element('#right', timeout=10)
        dash_duo.multiple_click('#right', clicks=1)
>       dash_duo.wait_for_contains_text('#log', text="right", timeout=10)

test_dash_mp.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../miniconda3/envs/bla/lib/python3.8/site-packages/dash/testing/browser.py:326: in wait_for_contains_text
    return self._wait_for(
../../miniconda3/envs/bla/lib/python3.8/site-packages/dash/testing/browser.py:244: in _wait_for
    return _wait.until(method(*args), msg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.support.wait.WebDriverWait (session="bd077168b1656e683391282a6b686227")>
method = <dash.testing.wait.contains_text object at 0x7f22a9135760>
message = 'text -> right not found inside element within 10s'

(...)
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message: text -> right not found inside element within 10s

../../miniconda3/envs/bla/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:89: TimeoutException
----------------------------------------- Captured stdout call ------------------------------------------
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "dash_mp" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 test_dash_mp.py ⨯                                                                        100% ██████████
=========================================== warnings summary ============================================
test_dash_mp.py::test_app_no_errors
test_dash_mp.py::test_click

======================================== short test summary info ========================================
FAILED test_dash_mp.py::test_click - selenium.common.exceptions.TimeoutException: Message: text -> rig...

Results (15.33s):
       1 passed
       1 failed
         - test_dash_mp.py:18 test_click

```
When I open the dev tools in Chrome while running the tests, I get the following message in the console:
```
message: 
  Overlapping wildcard callback outputs
HTML: 
  In the callback for output(s):
  {"id":"log","idx":0,"prop":"children"}.data
Output 0 ({"id":"log","idx":0,"prop":"children"}.data)
overlaps another output ({"id":"log","idx":0,"prop":"children"}.data)
used in a different callback.
```

---

P.S. Running the tests separately works:
```
❯ pytest test_dash_mp.py::test_app_no_errors
Test session starts (platform: linux, Python 3.8.8, pytest 7.0.1, pytest-sugar 0.9.4)
rootdir: /home/rafael/Desktop/dash_mp_example
plugins: Faker-6.6.0, flaky-3.7.0, sugar-0.9.4, requests-mock-1.9.3, dash-2.0.0, cov-3.0.0, anyio-3.3.4
collecting ... 
 test_dash_mp.py ✓                                            100% ██████████
=============================================================================

Results (2.42s):
       1 passed
```

```
pytest test_dash_mp.py::test_click
Test session starts (platform: linux, Python 3.8.8, pytest 7.0.1, pytest-sugar 0.9.4)
rootdir: /home/rafael/Desktop/dash_mp_example
plugins: Faker-6.6.0, flaky-3.7.0, sugar-0.9.4, requests-mock-1.9.3, dash-2.0.0, cov-3.0.0, anyio-3.3.4
collecting ... 
 test_dash_mp.py ✓                                            100% ██████████
============================================================================= 

Results (2.76s):
       1 passed
```

**Comment by emilhe** [comment]
Ah, yes, I guess that makes sense. You are using a fixture, which is only initialized once, but you are calling `start_server` twice. I believe that will run the multiplexer logic twice. I believe you can avoid the issue by changing the fixture to a function that creates a new `DashProxy` object every time. The performance difference should be negligible.

**Comment by RafaelWO** [comment]
Thanks for your quick answer!

> I believe you can avoid the issue by changing the fixture to a function that creates a new `DashProxy` object every time.

Ok, but how can I then ensure that the new `DashProxy` object also has all callbacks and the layout of the "actual" app?

**Comment by RafaelWO** [comment]
@emilhe I got it to work by changing the fixture as follows:
```Python
@pytest.fixture
def dash_app():
    from index import app as _app
    app = DashProxy(
        name=__name__,
        suppress_callback_exceptions=True,
        transforms=[
            MultiplexerTransform(),
        ]
    )
    app.layout = _app.layout
    app.callbacks = _app.callbacks
    yield app
```

This works in my actual app but weirdly not in the example code provided above (maybe I'm missing something).

**Comment by emilhe** [comment]
Yes, that should work since you are now creating a new object each time (rather than re-using the app object) :)

**Comment by RafaelWO** [comment]
Thanks for the example! This works perfectly for the MWE but if I use this in my real app, I get errors in the browser console:
```
{'level': 'SEVERE',
  'message': 'http://localhost:8050/assets/main.css?m=1646993475.9256864 - '
             'Failed to load resource: the server responded with a status of '
             '404 (NOT FOUND)',
```
Apparently, it is not able to load my custom `.css` files anymore. Any ideas? Is this something to do with the `hijack` function?

**Comment by RafaelWO** [comment]
FYI: I was able to fix the above by providing the path to the assets folder directly in the init function:
```Python
@pytest.fixture
def dash_app():
    from index import app as _app
    app = DashProxy(suppress_callback_exceptions=True, assets_folder='path/to/assets'))
    _app.hijack(app)
    yield app
```
Maybe some loading of assets is done before starting the server.

**Comment by emilhe** [comment]
Ah, yes. It's because the assets path is burned into the dash object on init, the the hijack function can't change it.
