### ISSUE TITLE
How to clear the cache of ServersideOutput and it is possible to cache in memory?

### ISSUE THREAD

**Issue by qicqic99** [thedirtyfew/dash-extensions#82]
Hi all, first, thanks for providing the amazing library.

Is there a method to clear cache file?

Could ServersideOuput cache in memory?
I want to build  a callback function for slice the data, then share to other callback function.

 Thanks.

**Comment by emilhe** [comment]
Thanks! You can force reload data via a kwarg, if you want to delete the whole cache, you cam just delete the folder using shutil. You can do in memory storage using e.g. Redis

**Comment by qicqic99** [comment]
Thanks.
That works for me.
