### ISSUE TITLE
How to set the external_stylesheets?

### ISSUE THREAD

**Issue by qicqic99** [thedirtyfew/dash-extensions#83]
`from dash_extensions.enrich import DashProxy`

`app = DashProxy(external_stylesheets=[dbc.themes.BOOTSTRAP])`

The external_stylesheets is not working, when import Dash from enrich.

Thanks

**Comment by qicqic99** [comment]
import Dash instead of DashProxy, it works

**Comment by emilhe** [comment]
There should be difference between using `Dash` and `DashProxy` objects in this regard. The `Dash` object just auto loads transforms. Could you post an MWE?
