### ISSUE TITLE
Cannot connect to redis server

### ISSUE THREAD

**Issue by ronscoder** [thedirtyfew/dash-extensions#85]
I tried the following to connect to redis-server: 

`html.Div(id="message", className='p-4 border'),
 WebSocket(url='ws://127.0.0.1:6379/1', id='ws')`

But received the following error in redis-server terminal:

`# Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.`
`
Any work around to resolve this error?

**Comment by emilhe** [comment]
It looks like to you are trying to connect the websocket directly to your Redis server. Are you sure that is supported? I would expect that you would "something in between" to map the data from the Redis server into the appropriate websocket messages.
