### ISSUE TITLE
How to set Timeout using ServersideOutput and Memoize?

### ISSUE THREAD

**Issue by zjuzhfbloodz** [thedirtyfew/dash-extensions#87]
I am new to Dash-Extensions and wonder how to set a timeout parameter using ServersideOutput and Memoize like cache.memoize(timeout=60)?
BTW, thank u for the dash-extensions package and it really helps me a lot!

**Comment by emilhe** [comment]
Thanks! If you want to set a timeout, you can do it when you initialize the caching backend. However, note that if the cache is cleared while a Dash application is running, the app will crash. Hence is **not** recommended to use timeouts, except maybe large ones (say, 24 hours).

**Comment by zjuzhfbloodz** [comment]
OK, that's just what I want and I will set 24 hours for timeout.
