### ISSUE TITLE
Websocket for async long operations not compiling

### ISSUE THREAD

**Issue by ishi-xibo** [thedirtyfew/dash-extensions#88]
hi. I refer to the example at: https://github.com/thedirtyfew/dash-extensions/blob/master/examples/websocket_long_process.py

run_server(app) doesn't compile in debug or non-debug mode. the websocket handler doesn't trigger if I don't use run_server but use app.run_server.

Any guidance is appreciated.

**Comment by emilhe** [comment]
Could you elaborate on why you are compiling Python code?

**Comment by ishi-xibo** [comment]
Sorry I misspoke. I wasn't compiling. I was just executing it using
Pycharm. If I use it as-is, it must hangs, and doesn't start the server
without any error. If I replace run_server with app.run_server, the server
starts but the web sockets don't fire.

**Comment by ishi-xibo** [comment]
For reference I am using the latest version of dash-extensions-> 0.0..57 for running the test.. here is the screenshot in the normal mode. It just hangs. No changes were made to your code.. also showing the screenshot of the warning in the debugger mode. Your code is instrumental in our code (ServersideOutput is amazing work). Appreciate if you can help unlock why ws_handler is not getting invoked


![image](https://user-images.githubusercontent.com/75040321/123541254-2150fa80-d776-11eb-9a77-bf24c489fb1d.png)

![image](https://user-images.githubusercontent.com/75040321/123541278-45144080-d776-11eb-8d31-cc77d7cd8fd5.png)

**Comment by emilhe** [comment]
Did you try to open the app, i.e. go to http://localhost:5000/? I am not sure the debugger will work when the app is launched via the `run_server` function.

**Comment by ishi-xibo** [comment]
Ah.. I waiting on some indication from Pycharm that the code is running. It is indeed running. Thank you so much for the fast response. Truly appreciate it.
