### ISSUE TITLE
missing dash_extensions/async-lottie.js ?

### ISSUE THREAD

**Issue by wujohn1990** [thedirtyfew/dash-extensions#95]
Hi,

I was trying to run the [websocket example](https://github.com/thedirtyfew/dash-extensions#websocket).

However I had this error:
`FileNotFoundError: [Errno 2] No such file or directory: '..../anaconda3/lib/python3.7/site-packages/dash_extensions/async-lottie.js'`

I installed dash-extensions via pip. Do I need to build/install anything else?

Thanks

**Comment by pvabreu7** [comment]
I've had the same problem here as well.

**Comment by emilhe** [comment]
Something seems to have gone wrong in the build process. Please revert to 0.0.58 for now.

**Comment by emilhe** [comment]
I believe this issue has been resolved. Please try with `dash-extensions==0.0.60`.

**Comment by pvabreu7** [comment]
Problem fixed for me. Thanks, @emilhe !
